### ISSUE TITLE
Allow dh compute key with elliptic curves

### ISSUE THREAD

**Issue by FourierTransformer** [zhaozg/lua-openssl#102]
It would be great if we could do a dh_compute_key (similar to Ruby's http://ruby-doc.org/stdlib-2.0.0/libdoc/openssl/rdoc/OpenSSL/PKey/EC.html#method-i-dh_compute_key) with two EC pkey objects.

**Comment by zhaozg** [comment]
Not do deep work, just simply wrap ECDH_compute_key
