### ISSUE TITLE
why this error?

### ISSUE THREAD

**Issue by otgo** [zhaozg/lua-openssl#109]
lua: error loading module 'openssl' from file '/usr/local/lib/lua/5.2/openssl.so':
        /usr/local/lib/lua/5.2/openssl.so: undefined symbol: X509_ALGOR_cmp

**Comment by zhaozg** [comment]
please look at https://github.com/zhaozg/lua-openssl/issues/94
If not same with #94, please give me os version, and openssl version

**Comment by jarriztg** [comment]
```
root@vps273405:~# openssl version
OpenSSL 1.0.2k  26 Jan 2017

root@vps273405:~# cat /etc/*version
stretch/sid
Ubuntu 16.04 LTS (Xenial Xerus)
```
I have openssl lua installed with:
`luarocks install openssl --server=https://rocks.moonscript.org/dev`

**Comment by jarriztg** [comment]
Now I have openssl "OpenSSL 1.1.1-dev  xx XXX xxxx" but i have the same error

**Comment by zhaozg** [comment]
I want to know then X509_ALGOR_cmp API is in your libssl.so or libcrypto.so. and can you try build openssl from source code, and check lua-openssl link to right openssl, maybe you need change some config in makefile.

**Comment by zhaozg** [comment]
Fail to compile when openssl missing X509_ALGOR_cmp, look https://github.com/zhaozg/lua-openssl/commit/411fd86b8e28522ded4b70a7d227d52a22f3c86f

**Comment by zhaozg** [comment]
luarocks install openssl --server=https://rocks.moonscript.org/dev LIBFLAG="-Wl,--no-undefined"
