### ISSUE TITLE
Getting pointer values instead of referenced values

### ISSUE THREAD

**Issue by bclodius** [zhaozg/lua-openssl#110]
Hi @zhaozg I am not sure if my description is "correct" but while attempting the sample code from https://github.com/zhaozg/lua-openssl/issues/75#issuecomment-139775239 I am getting below output.  I am wondering why I'm not able to get values for many of the objects: notafter, notbefore, etc.

I am using luajit (is this why)?
```
LuaJIT 2.1.0-beta2
```

```
issuer=openssl.x509_name: 0x40887d48
	version=2
	ca=false
	hash=857f039c
	valid=false
	purposes={
		any=true
		sslserver=true
		nssslserver=true
		ocsphelper=true
		any CA=true
	purposes=}
	notBefore=openssl.asn1_time: 0x40887e38
	subject=openssl.x509_name: 0x40887c88
	sig=���`����\3O��ˀ���/�����E��?�l1�o�g�`9ǭR�ѳl]:��}���]�#
	extensions={
		1=openssl.x509_extension: 0x408882a8
		2=openssl.x509_extension: 0x408882f0
		3=openssl.x509_extension: 0x40888318
		4=openssl.x509_extension: 0x40888370
		5=openssl.x509_extension: 0x40888398
		6=openssl.x509_extension: 0x40888340
	extensions=}
	sig_alg=openssl.x509_algor: 0x40887d70
	notAfter=openssl.asn1_time: 0x40887e88
	name=/CN=ngate.ru
	serialNumber=openssl.asn1_integer: 0x40887d08
```

**Comment by zhaozg** [comment]
please look at http://zhaozg.github.io/lua-openssl/modules/asn1.html#Class_asn1_string, and you need get data from asn1_string by `:data`, eg, notBefore:data(), and all asn1_* object can use as asn1_string.

openssl.x509_extension should be handle as http://zhaozg.github.io/lua-openssl/modules/x509.extension.html object

**Comment by zhaozg** [comment]
please check https://github.com/zhaozg/lua-openssl/commit/baa229ad5ef5f908e3f11c52e48ad54ae1109506
