### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by bbxc** [zhaozg/lua-openssl#112]
[root@localhost lua-openssl]# make
gcc -g -Wall -fPIC   -I/usr/local/include/lua5.1   -DPTHREADS  -Ideps -c -o src/csr.o src/csr.c
src/csr.c: 在函数‘X509_REQ_to_X509_ex’中:
src/csr.c:56: 错误：提领指向不完全类型的指针
src/csr.c:58: 错误：提领指向不完全类型的指针
src/csr.c:59: 错误：提领指向不完全类型的指针
src/csr.c:59: 警告：隐式声明函数‘M_ASN1_INTEGER_new’
src/csr.c:61: 错误：提领指向不完全类型的指针
src/csr.c:73: 错误：提领指向不完全类型的指针
src/csr.c:75: 错误：提领指向不完全类型的指针
make: *** [src/csr.o] 错误 1
***********************
I got this error, how to solve？

**Comment by gnought** [comment]
Please see PR #113

**Comment by zhaozg** [comment]
You can remove  -Wall from makefile, and try again.

**Comment by bbxc** [comment]
I change openssl version 1.1.0f ->1.0.2j,this no "make error"。but：
more /usr/local/openresty/lua-openssl/deps/lua-compat/c-api/compat-5.3.c:551: undefined reference to `lua_pushnumber'
.....
do you hava QQ or weixin ID？

**Comment by gnought** [comment]
@bbxc You get the point. lua-openssl does not support OpenSSL v1.1.0+ well. There should be a lot of work and cleanup.

**Comment by bbxc** [comment]
@gnought thanks，I still did not solve the problem.  this not support “openresty”？
@zhaozg I sent a mail to your gmail mail，Can you reply and tell me instant contact or chat? tks!

**Comment by zhaozg** [comment]
I think https://github.com/zhaozg/lua-openssl/commit/fa60af36d178b971217a04dbada65d9006b05e6c commit will make you happy.
