### ISSUE TITLE
Install the rock in mac os x with luajit 

### ISSUE THREAD

**Issue by ealogar** [zhaozg/lua-openssl#119]
Withe the latest luajit bundled in openresty when installing in macosx with brew, that's version LuaJIT 2.1.0-beta2 and openresty nginx version: openresty/1.11.2.3 the installation with luarocks failed with that error:

```sh
MACOSX_DEPLOYMENT_TARGET="10.3" cc -fPIC -I/usr/local/opt/openssl/include -I/usr/local/Cellar/openresty/1.11.2.3/luajit/include/luajit-2.1 -g -Wall -Wno-unused-value -DPTHREADS -Ideps -c -o src/asn1.o src/asn1.c
In file included from src/asn1.c:8:
In file included from src/private.h:3:
deps/lua-compat/c-api/compat-5.3.h:152:19: error: static declaration of 'luaL_setfuncs' follows non-static declaration
COMPAT53_API void luaL_setfuncs (lua_State *L, const luaL_Reg *l, int nup);
                  ^
deps/lua-compat/c-api/compat-5.3.h:151:23: note: expanded from macro 'luaL_setfuncs'
#define luaL_setfuncs COMPAT53_CONCAT(COMPAT53_PREFIX, L_setfuncs)
                      ^
deps/lua-compat/c-api/compat-5.3.h:41:31: note: expanded from macro 'COMPAT53_CONCAT'
#define COMPAT53_CONCAT(a, b) COMPAT53_CONCAT_HELPER(a, b)
                              ^
deps/lua-compat/c-api/compat-5.3.h:40:38: note: expanded from macro 'COMPAT53_CONCAT_HELPER'
#define COMPAT53_CONCAT_HELPER(a, b) a##b
                                     ^
<scratch space>:169:1: note: expanded from here
luaL_setfuncs
^
/usr/local/Cellar/openresty/1.11.2.3/luajit/include/luajit-2.1/lauxlib.h:88:18: note: previous declaration is here
LUALIB_API void (luaL_setfuncs) (lua_State *L, const luaL_Reg *l, int nup);
```

I have googled a little bit and it's the same issue that lua-cjson had with the latest version of openresty, They fixed here: 
```http
https://github.com/openresty/lua-cjson/commit/55d22ef3bc5f512a9dadd84fd85895824dad73d9
```

As a workaround, I have fixed removing the definition of function in compat-5.3.c and .h as the funciton is already in luajit but I'm sure you will find a better solution.

@zhaozg if you fix this, you will update the rockspecs in luarocks repo ?
Thanks!

**Comment by ealogar** [comment]
In a RHEL7 with openresty version nginx version: openresty/1.11.2.4 and luajit LuaJIT 2.1.0-beta2 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/, this is not happening

**Comment by zhaozg** [comment]
@ealogar Thanks your information, now I have no time to do something for this, welcome PR or wait a few weeks

**Comment by zhaozg** [comment]
Please check head of lua-openssl, and ci is green now, more detail on  https://travis-ci.org/zhaozg/lua-openssl/jobs/263399477#L2003

**Comment by zhaozg** [comment]
luarocks install --server=http://luarocks.org/dev openssl OPENSSL_DIR=...
will work now.
