### ISSUE TITLE
lua-openssl vs openssl generate different encrypt results

### ISSUE THREAD

**Issue by akinwaleakc** [zhaozg/lua-openssl#123]
I am trying to perform a basic encryption by obtaining matching encrypt results for the same string "hello world" using lua-openssl and using plain openssl on the bash command line.

For the command below using aes-128-ecb cipher to encrypt the plain text "hello world" on bash shell, I get

## BASH
**echo "hello world" | openssl enc -e -a -aes-128-ecb -nosalt -K 5F4DCC3B5AA765D61D8327DEB882CF99**
iFzU4f4hkfae1bRHRnZ6qA==

## LUA-OPENSSL
**Using the library** (cipher: aes-128-ecb and same key as above) I obtain
MLiJ8M5Xx2yrBHcbnj1ztA==

The lua code used, taken from the library documentation sample, is shown below

local evp_cipher = openssl.cipher.get('aes-128-ecb')
local data = 'hello world'
local key = '5F4DCC3B5AA765D61D8327DEB882CF99'
local cdata = evp_cipher:encrypt(data, key)
base64.encode(cdata)

At this stage I am not sure what I am doing wrong. I suspect that I am not using the right bash openssl command options which are equivalent to the operation of the library. Any help will be really appreciated.

Thanks.

**Comment by zhaozg** [comment]
Please try
```lua
local evp_cipher = openssl.cipher.get('aes-128-ecb')
local data = 'hello world'
local key = '5F4DCC3B5AA765D61D8327DEB882CF99'
-- use key binary, not hex string, so you need do hex decode
local cdata = evp_cipher:encrypt(data, openssl.hex(key,false))
base64.encode(cdata)
```

**Comment by zhaozg** [comment]
please look at https://stackoverflow.com/questions/33160246/test-vectors-for-aes-128-ecb-and-openssl and do some check.
```lua
local openssl = require'openssl'
local evp_cipher = openssl.cipher.get('aes-128-ecb')

local data = 'hello world'
local key = '5F4DCC3B5AA765D61D8327DEB882CF99'
key = openssl.hex(key,false)

local cdata = evp_cipher:encrypt(data, key, iv)
print(openssl.base64(cdata))

local ddata = evp_cipher:decrypt(cdata, key, iv)
assert(ddata==data)
```
  got output y6Gz/s3WVi59hKsHsEDzIw==

and run
  > E:\msys64\usr\bin\openssl.exe enc -aes-128-ecb -nosalt -K   5F4DCC3B5AA765D61D8327DEB882CF99 -in plain -a

got same y6Gz/s3WVi59hKsHsEDzIw==
plian content is `hello world`

**Comment by zhaozg** [comment]
but 
> $ echo "hello world" |  openssl.exe enc -aes-128-ecb -nosalt -K 5F4DCC3B5AA765D61D8327DEB882CF99 -a 

got 
                                                     
iFzU4f4hkfae1bRHRnZ6qA==

**Comment by zhaozg** [comment]
and more info:
decrpt iFzU4f4hkfae1bRHRnZ6qA== will get "hello world\n'

**Comment by akinwaleakc** [comment]
Thanks alot. I included openssl.hex() function. Though i still obtain different cipher texts, it turns out the library successfully decrypts both encrypted data from openssl(bash i.e iFzU4f4hkfae1bRHRnZ6qA==)  and lua-openssl (i.e y6Gz/s3WVi59hKsHsEDzIw==) into the correct string "hello world".

**Comment by zhaozg** [comment]
@akinwaleakc

decrypt iFzU4f4hkfae1bRHRnZ6qA== will get `hello world\n`
decrypt y6Gz/s3WVi59hKsHsEDzIw==  will get `hello world`

please notice that `n`
