### ISSUE TITLE
How to pass a NULL bio to openssl.cms.verify?

### ISSUE THREAD

**Issue by prime89** [zhaozg/lua-openssl#130]
[cms example ](https://github.com/cloudmeter/openssl/blob/master/demos/cms/cms_ver.c)

i want to use ` openssl.cms.verify` , but the argument msg cannot be null, how to fix it ?

begging for help~

**Comment by zhaozg** [comment]
cms is not finish.maybe alter use pkcs7

**Comment by zhaozg** [comment]
https://github.com/zhaozg/lua-openssl/commit/2abd8ccf389103cbb9ef6b4a95af93ee7fe0ae3d
