### ISSUE TITLE
Ubuntu 16.04 error on luajit package load

### ISSUE THREAD

**Issue by ronakshahj** [zhaozg/lua-openssl#132]
I am trying to build lua-openssl on Ubuntu 16.04

```
Package luajit was not found in the pkg-config search path.
Perhaps you should add the directory containing `luajit.pc'
to the PKG_CONFIG_PATH environment variable
No package 'luajit' found
Target system: x86_64-linux-gnu
```

I have also installed OpenSSL 1.1.0 from source by following the steps in https://github.com/openssl/openssl/issues/4833

@zhaozg Any ideas on what I am missing ?

**Comment by zhaozg** [comment]
are you have lua or luajit installed, please try HEAD to build and install, I have install makefile for better lua dected
