### ISSUE TITLE
please update luarocks repo.

### ISSUE THREAD

**Issue by samchang8826** [zhaozg/lua-openssl#134]
luarocks install openssl --server=https://rocks.moonscript.org/dev

got failed under lua 5.1 as the same reason of:
https://travis-ci.org/zhaozg/lua-openssl/jobs/353801939

src/private.h:12:24: fatal error: compat-5.3.h: No such file or directory

Thank you.

**Comment by zhaozg** [comment]
Ok, please try again, I think fix this now.

**Comment by pejema** [comment]
Same problem

**Comment by gexueqiang1226** [comment]
Same problem
![image](https://user-images.githubusercontent.com/8774231/39395551-6e5653fa-4b12-11e8-88e7-50090cb9f9c2.png)

**Comment by zhaozg** [comment]
目前手头没电脑，等一个星期吧

**Comment by zhaozg** [comment]
rockspec updated, and please try again, http://luarocks.org/modules/zhaozg/openssl/scm-3
