### ISSUE TITLE
A unused function

### ISSUE THREAD

**Issue by xzzwandi** [zhaozg/lua-openssl#135]
openssl version is 1.0.1f
I saw a function in openssl.c have nerver be used：void CRYPTO_thread_cleanup(void);

![Uploading image.png…]()
I want to know if this is a hand error or the right one.  thanks

**Comment by zhaozg** [comment]
fixed in https://github.com/zhaozg/lua-openssl/commit/a35409db3137e30ea0e73dc9b5e5b2dc0adccd02.
