### ISSUE TITLE
线程安全问题

### ISSUE THREAD

**Issue by xzzwandi** [zhaozg/lua-openssl#136]
请问版本1.0.1f是线程安全的吗，怎么可以保障多线程安全？，谢谢

**Comment by fiendish** [comment]
I believe that the answer is yes. I use it with multiple simultaneous background threads.

**Comment by zhaozg** [comment]
Please look at https://github.com/zhaozg/lua-openssl/blob/master/src/th-lock.c, and https://github.com/zhaozg/lua-openssl/blob/f7fe81e7d559835ba70de44619799a820639d840/src/openssl.c#L290.

If you openssl support threads, lua-openssl will be thread safe.
