### ISSUE TITLE
The last commit with SRC additon breaks luarocks installation

### ISSUE THREAD

**Issue by ealogar** [zhaozg/lua-openssl#137]
With the last commit "add SRP(Secure Remote Password Protocol) support" the luarocks package tagged as scm-3 (default one) is using the new feature (I see in code that you tag as scm-4).

2018/05/22 15:42:10 [error] 5#5: init_by_lua error: ...ocal/openresty/luajit/share/lua/5.1/kong/tools/utils.lua:477: ...local/openresty/luajit/share/lua/5.1/luarocks/loader.lua:147: error loading module 'openssl' from file '/usr/local/openresty/luajit/lib/lua/5.1/openssl.so':
Error relocating /usr/local/openresty/luajit/lib/lua/5.1/openssl.so: luaopen_srp: symbol not found

This is an openresty installation with luajit bundled (kong).
Can you upload the scm-3 package without the new feature ? I suppose that the new feature was planned for you with scm-4 ?

**Comment by zhaozg** [comment]
please use https://luarocks.org/manifests/zhaozg/openssl-scm-5.rockspec
