### ISSUE TITLE
N00b/ documentation: Installation

### ISSUE THREAD

**Issue by nazneen84** [zhaozg/lua-openssl#138]
First of all, thank you for this project!

this project is a pre-requite to a project I want to use: https://github.com/Seb35/nginx-ssl-variables
I am trying to install it on a base docker image openresty/openresty:alpine-fat so I can use the lua scripts in the project by Seb35.

My docker log looks like so (its tentative):

Step 9/12 : COPY lua-openssl /usr/local/lua-openssl
 ---> 91d485ee3eee
Step 10/12 : RUN cd /usr/local/lua-openssl;ls
 ---> Running in 8b819f8151a4
LICENSE
Makefile
Makefile.win
README.md
STATE.md
appveyor.yml
config.win
deps
ldoc
lib
openssl-scm-4.rockspec
src
test
Removing intermediate container 8b819f8151a4
 ---> a5edac0823dd
Step 11/12 : RUN make /usr/local/lua-openssl;
 ---> Running in 396e533620c7
make: Nothing to be done for '/usr/local/lua-openssl'.
Removing intermediate container 396e533620c7
 ---> 206846595b14
Step 12/12 : RUN make install /usr/local/lua-openssl

Do I need to use a specific version of Linux for this project to work?

I have even tried using the alpine image as opposed to the alpine fat, installed the alpine apk.
Then I get a different error that says stderror_s not found. What am I missing?

Thanks,

**Comment by nazneen84** [comment]
Just an update with more information

I am trying to build my docker image like so:

```
FROM openresty/openresty:alpine-fat

# Set the version
ENV RESTY_CONFIG_OPTIONS_MORE "--with-ngx_http_ssl_module"
EXPOSE 80
EXPOSE 443

RUN ls /usr/local/openresty/nginx/logs

COPY lualib /usr/local/openresty/nginx/lualib
RUN chown -R nobody:root /usr/local/openresty/nginx/lualib

# Connect to project network to get this to work
RUN apk add --update \
    openssl openssl-dev \
    lua5.2 luarocks luajit-dev  lua-socket   \
    git

RUN openssl version; luajit -v;  \
    git clone https://github.com/zhaozg/lua-openssl.git /usr/local/lua-openssl; \
    chown -R nobody:root /usr/local/lua-openssl;    \
    cd /usr/local/lua-openssl;  \
    make
# RUN make install /usr/local/lua-openssl
# && make clean
```
The error I am getting is:

```
cc -fpic   -I/usr/include/luajit-2.1   -g -Wall -Wno-unused-value -DPTHREADS -Ideps -Ideps/lua-compat -Ideps/auxiliar -c -o src/as
n1.o src/asn1.c
In file included from src/asn1.c:7:0:
src/openssl.h:13:22: fatal error: auxiliar.h: No such file or directory
 #include "auxiliar.h"
                      ^
compilation terminated.
make: *** [Makefile:88: src/asn1.o] Error 1
The command '/bin/sh -c openssl version; luajit -v;      git clone https://github.com/zhaozg/lua-openssl.git /usr/local/lua-openss
l;     chown -R nobody:root /usr/local/lua-openssl;        cd /usr/local/lua-openssl;      make' returned a non-zero code: 2

```
The file exists in the project. What am I missing?

**Comment by zhaozg** [comment]
[rockspec](http://luarocks.org/manifests/zhaozg/openssl-scm-5.rockspec) and README.md update, please look https://github.com/zhaozg/lua-openssl/commit/1932437707451b427ad3097180ce90b7aef4ce9
