### ISSUE TITLE
Makefile: detect luaver distribution!

### ISSUE THREAD

**Issue by d9k** [zhaozg/lua-openssl#139]
My lua distribution is installed by https://github.com/DhavalKapil/luaver and I have no `lua.h` at `/usr/local/include/lua5.2`. but at `~/.luaver/lua/5.2.4/include`.

```
 % make                          
Package luajit was not found in the pkg-config search path.
Perhaps you should add the directory containing `luajit.pc'
to the PKG_CONFIG_PATH environment variable
No package 'luajit' found
cc -fpic   -I/usr/local/include/lua5.2  -g -Wall -Wno-unused-value -DPTHREADS -Ideps -Ideps/lua-compat -Ideps/auxiliar -c -o src/asn1.o src/asn1.c
In file included from src/asn1.c:7:0:
src/openssl.h:10:17: fatal error: lua.h: No such file or directory
compilation terminated.
Makefile:88: recipe for target 'src/asn1.o' failed
make: *** [src/asn1.o] Error 1
```

**Comment by d9k** [comment]
Also installation by luarocks fails:

```
 % luarocks install openssl --server=https://rocks.moonscript.org/dev
Installing https://rocks.moonscript.org/dev/openssl-scm-3.rockspec
gcc -O2 -fPIC -I/home/d9k/.luaver/lua/5.2.4/include -c src/asn1.c -o src/asn1.o -DPTHREADS -I${OPENSSL_INCDIR} -I/usr/include -Ideps -Ideps/lua-compat
In file included from src/asn1.c:7:0:
src/openssl.h:13:22: fatal error: auxiliar.h: No such file or directory
compilation terminated.

Error: Build error: Failed compiling object src/asn1.o
```

**Comment by d9k** [comment]
@zhaozg, "use extern auxiliar lib" https://github.com/zhaozg/lua-openssl/commit/61726cdd22da133b7f2584d5d46476d9adcb9c4d breaks luarocks installation!

Was able to install using the older repo revision

```
git checkout e923252b28cff43add6382853cc85ed888c4474b .
luarocks make openssl-scm-4.rockspec
``

(`luarocks make` ignores `source.url`, the sources from current directory used instead)

**Comment by zhaozg** [comment]
yes，something need maybe I have time weekend

**Comment by djjames72** [comment]
I am running into the luarocks issue as well. @d9k Thanks for that tip. 

Also @zhaozg thanks for all your work on the module

**Comment by zhaozg** [comment]
[rockspec](http://luarocks.org/manifests/zhaozg/openssl-scm-5.rockspec) and [README.md](https://github.com/zhaozg/lua-openssl#howto) update, please look https://github.com/zhaozg/lua-openssl/commit/1932437707451b427ad3097180ce90b7aef4ce9 
I encourage update Makefile to satisfy yourself, because I busy on my job and maybe later to handle this.

**Comment by d9k** [comment]
@zhaozg, I reinstalled the package with 

`luarocks install openssl --server=https://rocks.moonscript.org/dev`
and got error 

```
lua: error loading module 'openssl' from file '/home/d9k/.luaver/luarocks/2.4.4_5.2/lib/lua/5.2/openssl.so':                                          [0/1971]
        /home/d9k/.luaver/luarocks/2.4.4_5.2/lib/lua/5.2/openssl.so: undefined symbol: CRYPTO_mem_leaks_fp
```

at `local openssl = require 'openssl'` line in my code

**Comment by zhaozg** [comment]
Can you tell me your openssl version?

**Comment by d9k** [comment]
@zhaozg, I had no problems with revision e923252b28cff43add6382853cc85ed888c4474b.
openssl version is `1.1.0h-2.0+ubuntu16.04.1+deb.sury.org+1`

**Comment by fovecifer** [comment]
@d9k @zhaozg  I fix this error and make a PR #142 
it works in my environment

**Comment by fovecifer** [comment]
my PR not work.
I fork this project and remove "CRYPTO_mem_leaks_fp" code in openssl.c
so my code works very well as before, I think there must be something wrong with the 
"OPENSSL_NO_STDIO" macro, but I do not know why.
I use lua-openssl in openresty, so lua-openssl is also compile with openssl-1.1.0h

**Comment by zhaozg** [comment]
I will do some test build with openssl-1.1.x, anyway thansk @fovecifer

**Comment by zhaozg** [comment]
> 1.1.0 fail, 1.0.2 and 1.1.0 pass

Please wait until weekend.

**Comment by JaysonStangel** [comment]
Good Morning, I am having the same problems. Here is the error message I receive:

lua: error loading module 'openssl' from file '/home/gjstangel/lib/lua/5.3/openssl.so':
        /home/gjstangel/lib/lua/5.3/openssl.so: undefined symbol: CRYPTO_mem_leaks_fp

my versions of openssl is: OpenSSL 1.1.0j  20 Nov 2018

Any help would be appreciated.
