### ISSUE TITLE
How to  sha256 with RSA?

### ISSUE THREAD

**Issue by d9k** [zhaozg/lua-openssl#140]
Hello! How to use this library to sign message string with private key?

As https://developers.google.com/identity/protocols/OAuth2ServiceAccount says:

> Sign the UTF-8 representation of the input using SHA256withRSA (also known as RSASSA-PKCS1-V1_5-SIGN with the SHA-256 hash function) with the private key obtained from the Google API Console. The output will be a byte array.

How can I sign message with SHA256withRSA?

**Comment by d9k** [comment]
hope I did it right..

```
local openssl = require 'openssl'

local message = 'test message'

local evp_pkey = openssl.pkey.read(
  private_key_string,
  true -- is private
)

local signature = evp_pkey:sign(message, 'sha256')
```

**Comment by zhaozg** [comment]
Yes, you are right
