### ISSUE TITLE
Compilation warnings

### ISSUE THREAD

**Issue by turchanov** [zhaozg/lua-openssl#149]
On RHEL7 with openssl-1.0.2k-12.0.1.el7.x86_64.
With current master (18d4cbb0) compilation of src/x509.c and src/xalgor.c produces series of warnings:
```
src/x509.c: In function ‘openssl_x509_parse’:
src/x509.c:547:5: warning: passing argument 1 of ‘X509_get0_signature’ from incompatible pointer type [enabled by default]
     X509_get0_signature(&psig, &palg, cert);
     ^
In file included from src/openssl.h:20:0,
                 from src/x509.c:10:
/usr/include/openssl/x509.h:837:6: note: expected ‘struct ASN1_BIT_STRING **’ but argument is of type ‘const struct ASN1_BIT_STRING **’
 void X509_get0_signature(ASN1_BIT_STRING **psig, X509_ALGOR **palg,
      ^
...
```
These warnings are caused by commit b19bd99ed which does these changes (only one changeset is shown):
https://github.com/zhaozg/lua-openssl/commit/b19bd99eda3b35cb628dcd114dbe2d1163a8c4af#diff-103975d0484305fc18fb6493374ab50eL543
```diff
-    X509_ALGOR *palg = NULL;
-    ASN1_BIT_STRING *psig = NULL;
+    const X509_ALGOR *palg = NULL;
+    const ASN1_BIT_STRING *psig = NULL;

X509_get0_signature(&psig, &palg, cert);
```
Definition of `X509_get0_signature` in /usr/include/openssl/x509.h for OpenSSL-1.0.2k 
```
void X509_get0_signature(ASN1_BIT_STRING **psig, X509_ALGOR **palg,
                         const X509 *x);
```
Removing `const` specifier from local variable declarations fixes the warning. It usually a good practice to declare a function argument with `const` BUT what the point in setting `const` modifier to variables here?

**Comment by zhaozg** [comment]
1.1.x need const, api define changed,need do more work to fix warnings on many openssl version,welcome PR

I am busy now and follow many days

**Comment by zhaozg** [comment]
Please fetch HEAD
