### ISSUE TITLE
Not Compatible with Nginx(Openresty) ？

### ISSUE THREAD

**Issue by xliuqq** [zhaozg/lua-openssl#151]
I use lua-openssl-scm-5, openresty 1.13.6.2, openssl 1.0.2k。

when nginx reload，it failed and  error info is : 

2018/12/18 21:33:53 [notice] 28600#0: using the “epoll” event method
2018/12/18 21:33:53 [notice] 28600#0: start worker processes
2018/12/18 21:33:53 [notice] 28600#0: start worker process 28968
2018/12/18 21:33:53 [notice] 28600#0: start worker process 28969
2018/12/18 21:33:53 [notice] 28600#0: start worker process 28970
2018/12/18 21:33:53 [notice] 28600#0: start worker process 28971
2018/12/18 21:33:53 [notice] 28600#0: start worker process 28972
2018/12/18 21:33:53 [notice] 28600#0: start worker process 28973
2018/12/18 21:33:53 [emerg] 28968#0: SSL_CTX_new() failed (SSL: error:140A90F1:lib(20):func(169):reason(241))
2018/12/18 21:33:53 [emerg] 28969#0: SSL_CTX_new() failed (SSL: error:140A90F1:lib(20):func(169):reason(241))
2018/12/18 21:33:53 [emerg] 28970#0: SSL_CTX_new() failed (SSL: error:140A90F1:lib(20):func(169):reason(241))
2018/12/18 21:33:53 [emerg] 28971#0: SSL_CTX_new() failed (SSL: error:140A90F1:lib(20):func(169):reason(241))
2018/12/18 21:33:53 [emerg] 28972#0: SSL_CTX_new() failed (SSL: error:140A90F1:lib(20):func(169):reason(241))
2018/12/18 21:33:53 [emerg] 28973#0: SSL_CTX_new() failed (SSL: error:140A90F1:lib(20):func(169):reason(241))
2018/12/18 21:33:53 [notice] 28606#0: gracefully shutting down

Here is the simplest customized nginx.conf to reproduce above problem.
``` nginx
init_by_lua_block {
   require("luarocks.loader")
    local cms = require(“openssl_scm_5-openssl.so”).cms
} 

init_worker_by_lua_block {
 -- empty content
}
```
However,  If I remove the 'init_worker_by_lua_block ', Kong or openresty can reload success.

Any advise or solution?

Thanks!

**Comment by InfoHunter** [comment]
This project is very interesting. Actually if lua-openssl could be compatible with NGINX (or other variants like tengine: https://github.com/alibaba/tengine), it will be very cool since NGINX Lua module's original SSL functionality has not so many OpenSSL APIs supported yet.

**Comment by zhaozg** [comment]
Worth doing it, can only invest in my free time. I have not even started to study NGNIX, maybe this can be a begin.

**Comment by InfoHunter** [comment]
> Worth doing it, can only invest in my free time. I have not even started to study NGNIX, maybe this can be a begin.

Great. Given that I am also a member of the Tengine project, I think I can help on this if I have adequate spare time.

**Comment by zhaozg** [comment]
duplicate with https://github.com/zhaozg/lua-openssl/issues/196

**Comment by zhaozg** [comment]
@xliuqq I have do some test about this, it works well with 0.7.7-0.
Please notice that keep lua-openssl and openresty/nginx with same version openssl library or source code
