### ISSUE TITLE
srp.h not available on RHEL7 

### ISSUE THREAD

**Issue by MadalinaPatrichi** [zhaozg/lua-openssl#152]
I've got the same issue that was described in #146 , however, I have not seen the actual solution described in the issue, therefore reopening.

Getting the following error while installing with luarocks on CentOS7:

`src/srp.c:4:25: fatal error: openssl/srp.h: No such file or directory
 #include <openssl/srp.h>
                         ^
compilation terminated.

Error: Build error: Failed compiling object src/srp.o`

**Comment by MadalinaPatrichi** [comment]
I can confirm that just by removing that dependency from the rockspec I can install it on my OS. However this needs to be published to rockspec or fixed in some other way

**Comment by MadalinaPatrichi** [comment]
Could you please also cut a new release so it can be used with luarocks?@zhaozg

**Comment by zhaozg** [comment]
Done, please visit http://luarocks.org/modules/zhaozg/openssl/scm-6
