### ISSUE TITLE
sm2 is nil

### ISSUE THREAD

**Issue by hadibu** [zhaozg/lua-openssl#154]
Hi Zhao,
I read the sm2 doc from https://zhaozg.github.io/lua-openssl/modules/sm2.html, but when I tried to use it said sm2 is nil. Is sm2 not implemented?
Thanks.

**Comment by zhaozg** [comment]
need openssl 1.1.x,  please try

**Comment by hadibu** [comment]
I have downloaded the latest openssl from https://www.openssl.org/source/openssl-1.1.1a.tar.gz.
and here is the output when I list the curves:
 ./apps/openssl ecparam -list_curves | grep SM2
SM2       : SM2 curve over a 256 bit prime field

btw, I am running on WSL, ubuntu 1804.
Thanks.

**Comment by zhaozg** [comment]
Please look at https://travis-ci.org/zhaozg/lua-openssl/jobs/493263654#L3419 and https://github.com/zhaozg/lua-openssl/blob/master/test/sm2.lua, you call use SM2 by https://zhaozg.github.io/lua-openssl/modules/pkey.html.

Sorry for accident of https://zhaozg.github.io/lua-openssl/modules/sm2.html, It's my private code.

**Comment by xjh1994** [comment]
@zhaozg 用pkey调用sm2，会提示只能用RSA或RSA2，请问是什么原因

**Comment by xjh1994** [comment]
是调用sm2的pkey.encrypt的时候

**Comment by xjh1994** [comment]
是调用sm2的pkey.decrypt的时候
