### ISSUE TITLE
how to use the api of lua-openssl to implement the command of "openssl cms verify"

### ISSUE THREAD

**Issue by timusketeers** [zhaozg/lua-openssl#155]
Hi,
I want to implement the command by code using lua-openssl: **openssl cms -verify -in cms_token -certfile sign.cert -CAfile ca.cert -inform PEM -nosmimecap -nodetach -nocerts –noattr**.  how should I use the API of lua-openssl to get the goal. Thanks

**Comment by zhaozg** [comment]
closed in https://github.com/zhaozg/lua-openssl/wiki/Interaction-openssl-cms
