### ISSUE TITLE
How to use AES in CCM mode ?

### ISSUE THREAD

**Issue by klepretr** [zhaozg/lua-openssl#156]
Hi !

I'm a new user of this module and I have an issue to use CCM.
In cipher list, I see 'aes-xxx-ccm' and I can select it with `openssl.cipher.get('aes-xxx-ccm')` but I obtain an `openssl.evp_cipher`object and I can't find method signature with arguments like `tag` for authentication or `add_auth`.

This interface implement crypt/decrypt with authentication or not ?

Thanks,

**Comment by zhaozg** [comment]
Lua-openssl is not support CCM or GCM.

I think should add some new API for CCM/GCM, but has no plan now.

Ref: 
1. https://wiki.openssl.org/index.php/EVP_Authenticated_Encryption_and_Decryption
2. http://www.fredriks.se/?p=23

**Comment by zhaozg** [comment]
closed in https://github.com/zhaozg/lua-openssl/issues/156, please look into https://github.com/zhaozg/lua-openssl/blob/master/test/issue%23156.lua#L9
