### ISSUE TITLE
Compilation issue with X509_NAME define on Win32 with Visual Studio

### ISSUE THREAD

**Issue by treahard** [zhaozg/lua-openssl#165]
In the openssl.h header file, I added the following to resolve what others have described as "The infamous win32 X509_NAME #define problem".

I was unable to compile on Visual Studio the latest lua-openssl.  This addition to the top of the header file reolved the issue for me.

#if defined(WIN32)
#include <windows.h>
#include <wincrypt.h>
#ifdef X509_NAME
/* wincrypt.h has already a different define... */
#undef X509_NAME
#endif
#endif

/* OpenSSL includes */

**Comment by zhaozg** [comment]
here https://github.com/zhaozg/lua-openssl/blob/master/config.win#L18
