### ISSUE TITLE
In ssl.lua, unpack is not declared local

### ISSUE THREAD

**Issue by treahard** [zhaozg/lua-openssl#167]
In ssl.lua, the following code inadvertently declares unpack as a global.

   unpack = unpack or table.unpack   

Should this be

   local unpack = unpack or table.unpack

???

**Comment by zhaozg** [comment]
welcome PR

**Comment by treahard** [comment]
A busy day today so I will send PR over the weekend.

My first time to PR so I hope I do it properly.

Tom


On Apr 24, 2019 at 6:38 PM, <George Zhao<mailto:notifications@github.com>> wrote:


welcome PR

**Comment by zhaozg** [comment]
Closed, thanks
