### ISSUE TITLE
# C [openssl.so+0xe5970] SSL_shutdown+0x30

### ISSUE THREAD

**Issue by treahard** [zhaozg/lua-openssl#172]
We are running a server using lua-openssl.  Every so often, we receive this error and it crashes the Java Virtual Machine.   We have pulled the error message from the crash logs.  Has anyone else experience this?  I have looked at the code and wonder if CHECK_OBJECT can ever return a null value.  If so, it is then passed to SSL_shutdown.

**Comment by zhaozg** [comment]
Can you provide a recurrence case?

**Comment by zhaozg** [comment]
No response
