### ISSUE TITLE
openssl/comp.h

### ISSUE THREAD

**Issue by Timothy-** [zhaozg/lua-openssl#176]
If openssl is compiled without compression, then openssl/comp.h does not exist.
This makes lua-openssl compilation fail here:
https://github.com/zhaozg/lua-openssl/blob/177dcf17ddb1f01100f87cc8351dc0bca4a81447/src/openssl.h#L26

Add something like this to fix this issue:

```
#if !defined(OPENSSL_NO_COMP)
#include <openssl/comp.h>
#endif
```

**Comment by Timothy-** [comment]
Also `COMP_zlib_cleanup` is undefined:
https://github.com/zhaozg/lua-openssl/blob/177dcf17ddb1f01100f87cc8351dc0bca4a81447/src/openssl.c#L444

**Comment by zhaozg** [comment]
Can you make a PR, thanks, I can't resolve it in times
