### ISSUE TITLE
lua生成的公私钥如何跟别的语言生成的公私钥通用

### ISSUE THREAD

**Issue by liaokuan4hub** [zhaozg/lua-openssl#189]
lua生成的公私钥打印出来是这种：
openssl.evp_pkey: 0x7fc19f89f4d8
openssl.evp_pkey: 0x7fc19f89f518

java和nodejs中生成公私钥是16进制这种：
publicKey:04411bdf746c2f8fa8fb02b7399d7e7f451be5e9cf2b56274bb3a8d273ee72e5ddb2645a7953dccd29b1c399e129a91daa8d27eb1880e2587fae37589fc14d9199
privateKey:14bf1017156184a4e6df025cf467938e72a3ee21957641840ec240d56c3c5a23

该怎么让它们通用呢，您那里是怎么解决的！

**Comment by zhaozg** [comment]
看 https://zhaozg.github.io/lua-openssl/

**Comment by studentcaoqc** [comment]
这个集成的openssl里，按照pkey.lua生成的公司钥格式是什么现在我还是没搞明白，感觉js和java中的sm2是一套，这个是单独的

**Comment by liaokuan4hub** [comment]
陆陆续续一个多月了，SM4加解密都通了，只是SM2lua生成的公私钥还是不知道怎么转成跟java等其他语言一样16进制格式，无法加验签，前辈能否提供个详细的方案，不胜感激！

**Comment by InfoHunter** [comment]
Requirements emerged a lot for SM algorithms these days...

**Comment by liaokuan4hub** [comment]
> Requirements emerged a lot for SM algorithms these days...

国密感觉更像是国家发展的折射。刚接触理解不到位，希望前辈们能指点一二，再次感谢。

**Comment by InfoHunter** [comment]
> 国密感觉更像是国家发展的折射。

咋说？
