### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by sbehrens** [zhaozg/lua-openssl#19]
Hello

I cannot build the project:

```
Package lua was not found in the pkg-config search path.
Perhaps you should add the directory containing `lua.pc'
to the PKG_CONFIG_PATH environment variable
No package 'lua' found
Package lua was not found in the pkg-config search path.
Perhaps you should add the directory containing `lua.pc'
to the PKG_CONFIG_PATH environment variable
No package 'lua' found
gcc -g -fPIC -Wall -fPIC -Wno-unused-value    -DPTHREADS  -Wall -fPIC -Wno-unused-value    -DPTHREADS  -c -o src/asn1.o src/asn1.c
In file included from src/asn1.c:7:0:
src/openssl.h:10:17: fatal error: lua.h: No such file or directory
compilation terminated.
make: *** [src/asn1.o] Error 1
```

What configuration file are we supposed to change?  The only one I see is `config.win` and I am on a linux box.

**Comment by 1003824904** [comment]
I add “export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig”，but it show same error

**Comment by zhaozg** [comment]
Makefile 没办法找到 Lua 相关头文件，可能是你的Lua没有安装的 PREFIX 不是 /usr/local, 这种情况下，你可以手动调整 Makefile 试试，或者使用 CMake 试试 https://github.com/zhaozg/lua-openssl#howto-5-build-with-cmake

**Comment by 1003824904** [comment]
> Makefile 没办法找到 Lua 相关头文件，可能是你的Lua没有安装的 PREFIX 不是 /usr/local, 这种情况下，你可以手动调整 Makefile 试试，或者使用 CMake 试试 https://github.com/zhaozg/lua-openssl#howto-5-build-with-cmake

谢谢！我试试。

**Comment by 1003824904** [comment]
使用如下命令编译成功，谢谢！：
export LUAJIT_DIR=/usr/local/openresty/luajit
cmake -Bbuild -H. -DOPENSSL_ROOT_DIR=... && cd build && make
