### ISSUE TITLE
openssl_ssl_ctx_new_ssl client mode

### ISSUE THREAD

**Issue by Timothy-** [zhaozg/lua-openssl#190]
Hi,

In commit 78971628cdcbee97802d2da9f77e272c7d0032ab the last parameter for openssl_ssl_ctx_new_ssl to indicate client/server mode became mandatory.

This is now a problem in luvit here:

https://github.com/luvit/luvit/blame/master/deps/tls/common.lua#L205

Where self.server could be nil resulting in:
`bad argument #3 to 'ssl' (boolean expected, got nil)`

**Comment by zhaozg** [comment]
I will update luvit to support last version.

**Comment by Timothy-** [comment]
If you decide to update luvit instead of lua-openssl, then you should update the lua-openssl doc:
https://github.com/zhaozg/lua-openssl/blob/master/src/ssl.c#L615

https://zhaozg.github.io/lua-openssl/modules/ssl.html#ssl_ctx:ssl

I just gave luvit as an example. I had to change my own code to cope with this change.

PS. could you add a link to the lua-openssl documentation in the topic of this repository? Then it is easier to find.
https://zhaozg.github.io/lua-openssl/index.html

**Comment by zhaozg** [comment]
It's a good advice, but poor document quality need to do more update and check, and my job almost cost of all time. So you know, I can't give an end time.

**Comment by zhaozg** [comment]
Please look at https://github.com/zhaozg/lua-openssl/commit/d27bf501ff7544fc4a1ded512afca085b7ec4499

The commit make https://zhaozg.github.io/lua-openssl/modules/ssl.html#ssl_ctx:ssl compat with old version. and update luvit is not a good idea.
