### ISSUE TITLE
digest:final differ from LuaCrypto

### ISSUE THREAD

**Issue by doub** [zhaozg/lua-openssl#193]
When using the crypto.lua, the following differ from LuaCrypto:

local d = crypto.digest.new'sha1'
for chunk in chunks() do d:update(chunk) end
local h = d:final(nil, true)

In LuaCrypto this would give the raw hash, with lua-openssl this gives the hexadecimal hash.

This can be fixed either by adjusting the lua-openssl evp_digest_ctx:final to behave like LuaCrypto, or adding a complete wrapper for the object in crypto.lua. I can write a pull request for you if you tell me which option (could be a third one) you prefer.

**Comment by zhaozg** [comment]
closed by https://github.com/zhaozg/lua-openssl/commit/eb9f3775f3911f4f0a1eecb7493dd4aeae84ecaf

**Comment by doub** [comment]
eb9f377 doesn't fix this problem.

**Comment by zhaozg** [comment]
sorry, reopen it

**Comment by zhaozg** [comment]
here http://mkottman.github.io/luacrypto/manual.html#reference
```
digest:final([string] [, raw])
Generates the message digest for the loaded data, optionally appending on new data provided by string prior to hashing. The optional raw flag, defaulted to false, is a boolean indicating whether the output should be a direct binary equivalent of the message digest, or formatted as a hexadecimal string (the default).
```
raw = true output binary
raw = false[default] output hexadecimal

but in lua-openssl, https://zhaozg.github.io/lua-openssl/modules/digest.html#evp_digest_ctx:final
```
raw boolean binary or hex encoded result, default true for binary result
```

Sorry, I can not make lua-openssl api to compat with luacrypto, but a [compat](https://github.com/zhaozg/lua-openssl/blob/master/lib/crypto.lua#L18) lib to provide a luacrypto layer.

@doub What is your ideas?

**Comment by zhaozg** [comment]
https://github.com/zhaozg/lua-openssl/blob/260555ef6dd83c058a0b4fd488ed4b5e382d9c60/lib/crypto.lua#L17-L19
change to 
```lua
M.digest = openssl.digest
local dm = {}
dm.__call = function(self,alg,msg,raw)
    if raw==nil then raw=false end
    return M.digest.digest(alg,msg,raw)
end
```

**Comment by zhaozg** [comment]
Ok, it's a simply question, and sorry for I am gone.

I have update document for this file:///Users/zhaozg/work/zhaozg/lua-openssl/modules/digest.html#evp_digest_ctx:final

msg in `local h = d:final(msg, true)`  must be string, if it is nil, it will shift as raw, so lua-openssl will output hex, you can change it to `h = d:final(true)` h will be binary.

**Comment by zhaozg** [comment]
May I close this issue.

**Comment by doub** [comment]
I'm not sure I've been clear. The behaviour of openssl.evp_digest_ctx:final(nil, true) is different from the original LuaCrypto's crypto.digest:final(nil, true). If you want your lib/crypto.lua module to be a drop-in replacement for the original LuaCrypto, then you need to do the behaviour conversion.

**Comment by zhaozg** [comment]
It need a lots work to full compat with LuaCrypto in C native apis. so I tend to do that in lua layer. 

If narrow down to only digest:final(),  need to update https://github.com/zhaozg/lua-openssl/blob/master/src/digest.c#L35, use  `int top = lua_gettop(L)`, and check top value. 

if top==1 then raw = false(default).
if top==2 then raw=lua_toboolean(L, 2).
if top==3 then in=lua_tolstring(L, 2, &l), raw=lua_toboolean(L, 3).

So

**Comment by doub** [comment]
Something like this, yes. Your link to L35 seems wrong. Did you mean a different line? If you're changing static LUA_FUNCTION(openssl_evp_digest_final) then you need to account for the self argument too.

**Comment by zhaozg** [comment]
sorry, It is L355, static LUA_FUNCTION(openssl_evp_digest_final)

**Comment by doub** [comment]
Yes. If you're happy for me to change this function a little bit, then I will do the change, test it and submit a merge request soon.

**Comment by zhaozg** [comment]
> Yes. If you're happy for me to change this function a little bit, then I will do the change, test it and submit a merge request soon.

Ok, please take care of compatible with existing interfaces

**Comment by zhaozg** [comment]
closed by https://github.com/zhaozg/lua-openssl/pull/198, thank you @doub
