### ISSUE TITLE
timezone not defined in MSVC >= 2015

### ISSUE THREAD

**Issue by fiendish** [zhaozg/lua-openssl#199]
calls to timezone should be replaced with _get_timezone if MSVC is 2015 (_MSC_VER 1900) or higher

**Comment by zhaozg** [comment]
Thanks, if you can, please send a PR.

**Comment by fiendish** [comment]
I will try. Right now I am having a similar problem as https://github.com/zhaozg/lua-openssl/issues/197. I think it is because Appveyor's x64 static libraries for openssl do not match the version of MSVC.

**Comment by zhaozg** [comment]
I'm not focus on #197, I think the headers and linked libs are mismatch, maybe some OPENSSL_XXX_DIR setting wrong values.

**Comment by zhaozg** [comment]
close by https://github.com/zhaozg/lua-openssl/commit/cb3529a793a08dcb6f225e1839c0e4dd18067c82
