### ISSUE TITLE
Build from source fails

### ISSUE THREAD

**Issue by jl2035** [zhaozg/lua-openssl#202]
I'm trying to follow instructions from the readme file:

make
make install
make clean

I fail at 1st step: src/openssl.h:10:10: fatal error: lua.h: No such file or directory

I've noticed that #19 had the same problem as me, but I don't think I can set the PKG_CONFIG_PATH, as I don't have the "pkgconfig" directory inside /usr/local/lib/.

**Comment by terryhy520** [comment]
use
```shell
find / -name "openssl.pc"
```
to find openssl config path.
then 
export it to ENV_Path by:
```shell
export PKG_CONFIG_PATH="/usr/local/ssl/lib/pkgconfig/"
```

**Comment by jl2035** [comment]
@terryhy520 thanks. Do you have any idea what my next error is about?

> make
> cc -fPIC  -I/usr/include/luajit-2.1  -Wall -Wno-unused-value -Wno-unused-function -DPTHREADS -Ideps -Ideps/lua-compat/c-api -Ideps/auxiliar -c -o src/asn1.o src/asn1.c
> In file included from src/asn1.c:11:0:
> src/openssl.h:13:10: fatal error: auxiliar.h: No such file or directory
>  #include "auxiliar.h"
>           ^~~~~~~~~~~~
> compilation terminated.
> Makefile:109: recipe for target 'src/asn1.o' failed
> make: *** [src/asn1.o] Error 1
