### ISSUE TITLE
Attempt to index a nil value (global 'openssl')

### ISSUE THREAD

**Issue by jl2035** [zhaozg/lua-openssl#203]
Not sure how, but I think I successfully installed this library and now I'm trying to implement the example from the docs.

```
local evp_cipher = openssl.cipher.get('des')
m = 'abcdefghick'
key = m
cdata = evp_cipher:encrypt(m,key)
m1  = evp_cipher:decrypt(cdata,key)
assert(m==m1)
```
I'm getting the following error message, when I try to execute that script:

```
lua5.3: test2.lua:1: attempt to index a nil value (global 'openssl')
stack traceback:
	test2.lua:1: in main chunk
	[C]: in ?
```

Should this work out-of-the-box?

==========================EDIT==========================

I've noticed that the import is missing, but after adding

`openssl = require('openssl')`

as the first line of the script, I still don't get very far. It's just another error:

```
lua5.3: test2.lua:2: attempt to index a nil value (field 'cipher')
stack traceback:
	test2.lua:2: in main chunk
	[C]: in ?
```

**Comment by Legrandin** [comment]
Hitting the same problem on Ubuntu 18 which comes with openssl 1.1.0g.

**Comment by norcalli** [comment]
I'm having the same problem. After fixing pkg-config with `--keep-system-cflags --keep-system-libs`, I still don't have the openssl object being populated at all. It's just version and nothing else.

**Comment by jl2035** [comment]
So it this package working for anyone?

I was unsuccessful with luarocks and with building from source.

@zhaozg what's the meaning of the question mark? Do you need any additional information about this problem?

**Comment by terryhy520** [comment]
I'm having the same problem,
'''shell
ERROR: lua_openssl.lua:10: attempt to index field 'cipher' (a nil value)
stack traceback:
	init_worker_by_lua:45: in function <init_worker_by_lua:43>
	[C]: in function 'xpcall'
	init_worker_by_lua:52: in function <init_worker_by_lua:50>
'''
It seems that the system's default openssl loaded before lua-openssl.

can we rename the lib to luaopenssl when expose the namespace?
@zhaozg

**Comment by terryhy520** [comment]
> I'm having the same problem,
> 
> ```shell
> ERROR: lua_openssl.lua:10: attempt to index field 'cipher' (a nil value)
> stack traceback:
> 	init_worker_by_lua:45: in function <init_worker_by_lua:43>
> 	[C]: in function 'xpcall'
> 	init_worker_by_lua:52: in function <init_worker_by_lua:50>
> ```
> 
> It seems that the system's default openssl loaded before lua-openssl.
> 
> can we rename the lib to luaopenssl when expose the namespace?
> @zhaozg

I have workaroud my problem by renaming "openssl" to "luaopenssl" in makefile.
the root cause is the kong's builtin openssl loaded before openssl.so built by lua-openssl project.

**Comment by zhaozg** [comment]
https://github.com/luvit/luvi/blob/9da12caaf01337ef0609d07b2af9a5296c13922a/src/main.c#L107-L111

you can exporse lua-openssl as any name.
