### ISSUE TITLE
aes-256-gcm decrypt failed.

### ISSUE THREAD

**Issue by terryhy520** [zhaozg/lua-openssl#205]
- `uname -a` or OS info:
Linux host-10-31-30-41 3.10.0-327.62.59.83.h112.x86_64 #1 SMP Mon Jan 1 00:00:00 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- `openssl version` or OPENSSL_VERSION_TEXT in your opensslv.h:
OpenSSL 1.0.2k-fips  26 Jan 2017

- `lua -v` or `luajit -v`:
Lua 5.1.4  Copyright (C) 1994-2008 Lua.org, PUC-Rio

- `lua -e "print(require'openssl'.version())" or `luajit -e "print(require'openssl'.version())"`:
0.7.7	Lua 5.1	OpenSSL 1.0.2k-fips  26 Jan 2017

**Problem details**
aes-256-gcm encrypt ok, derypt failed.

**Steps/codes to reproduce the bug**
run the codes abc.lua below:
```lua
local luaopenssl = require('openssl')
local evp_cipher = luaopenssl.cipher.get('aes-256-gcm')
local m = 'hello world'
print('m:'..m)
local key = 'goodmorningu1234'
local iv = 'abcdabcdabcd1234'
local cdata = evp_cipher:encrypt(m,key,iv)
print('cdata:'..cdata)
print('iv:'..iv)
local m1  = evp_cipher:decrypt(cdata,key,iv)
print('m1:'..m1)
assert(m==m1)
```

**Expected result**
m:hello world
cdata:®PƨU)c75
iv:abcdabcdabcd1234
m1:hello world

**Additional context**
In fact decrypted failed:
m:hello world
cdata:®PƨU)c75
iv:abcdabcdabcd1234
lua: abc.lua:11: attempt to concatenate local 'm1' (a nil value)
stack traceback:
	abc.lua:11: in main chunk
	[C]: ?

changing the cipher to "aes128" works good both in encrypt and decrypt.
but the aes-256-gcm encrypt ok, decrypt failed.

**Comment by zhaozg** [comment]
Please look at here, https://github.com/zhaozg/lua-openssl/blob/master/test/issue%23156.lua#L63

quick encrypt/decrypt not support ccm/gcm, maybe need update document.
