### ISSUE TITLE
Error loading openssl module - undefined symbol: lua_getmetatable

### ISSUE THREAD

**Issue by hinawatts** [zhaozg/lua-openssl#213]
- `uname -a` or OS info: Ubuntu
- `openssl version` or OPENSSL_VERSION_TEXT in your opensslv.h: 0.7.8-0
- `lua -v` or `luajit -v`: 2.0.5
- `lua -e "print(require'openssl'.version())" or `luajit -e "print(require'openssl'.version())"`:

**Problem details**
I am trying to require openssl and getting error - error loading module 'openssl' from file '/etc/envoy/luas/lua_modules/lib/lua/5.1/openssl.so':
	/etc/envoy/luas/lua_modules/lib/lua/5.1/openssl.so: undefined symbol: lua_getmetatable

**Steps/codes to reproduce the bug**

**Comment by zhaozg** [comment]
Maybe you not run in a lua host program, and not link libluajit-5.1
