### ISSUE TITLE
Support Lua 5.4

### ISSUE THREAD

**Issue by glguy** [zhaozg/lua-openssl#219]
Could this library be updated to support Lua 5.4? My locally testing indicates that it compiles and works (at least for what I'm doing with the library) on 5.4. I don't know enough to assess how the 5.4 changes will impact this library.

**Comment by zhaozg** [comment]
close by https://github.com/zhaozg/lua-openssl/commit/8706c6453651c64cbed376eca0137cb87b5a69ed
