### ISSUE TITLE
Getting key modulus and exponent

### ISSUE THREAD

**Issue by namedgraph** [zhaozg/lua-openssl#224]
**Is your feature request related to a problem? Please describe.**
I want to get the modulus and exponent components of a (public) key.

**Describe the solution you'd like**
Ideally [`pkey`](https://zhaozg.github.io/lua-openssl/modules/pkey.html) should have dedicated methods, similar to Java's [`RSAKey::getModulus`](https://docs.oracle.com/javase/8/docs/api/java/security/interfaces/RSAKey.html#getModulus--) and [`RSAPublicKey::getPublicExponent`](https://docs.oracle.com/javase/8/docs/api/java/security/interfaces/RSAPublicKey.html#getPublicExponent--).

**Describe alternatives you've considered**
I can't see how to parse those values in Lua, will need to pass the whole public key to Java for now.

**Comment by zhaozg** [comment]
1.  pkey:parse() get  rsa raw object  https://zhaozg.github.io/lua-openssl/modules/pkey.html#evp_pkey:parse
2. raw:parse() get rsa factor table. https://github.com/zhaozg/lua-openssl/blob/master/test/rsa.lua#L5
