### ISSUE TITLE
TestCMS test fails

### ISSUE THREAD

**Issue by ConiKost** [zhaozg/lua-openssl#230]
- `uname -a` or OS info: Linux Galactica 5.11.11-gentoo #1 SMP Sun Apr 4 23:29:23 CEST 2021 x86_64 Intel(R) Atom(TM) CPU C2758 @ 2.40GHz GenuineIntel GNU/Linux

- `openssl version` or OPENSSL_VERSION_TEXT in your opensslv.h: OpenSSL 1.1.1k  25 Mar 2021
- `lua -v` or `luajit -v`: LuaJIT 2.0.5 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/
- `lua -e "print(require'openssl'.version())" or `luajit -e "print(require'openssl'.version())"`: 0.8.0	Lua 5.1	OpenSSL 1.1.1k  25 Mar 2021

**Problem details**
```
# Starting class: TestCMS
not ok 8	TestCMS.testCompress
# 6.cms.lua:19: bad argument #2 to 'uncompress' (only support string or openssl.bio)
```

**Steps/codes to reproduce the bug**
Run test TestCMS

**Expected result**
TestCMS will not fail.

**Comment by zhaozg** [comment]
Please make sure your openssl enable compress and compile with zlib support.

**Comment by ConiKost** [comment]
Thank you!
