### ISSUE TITLE
TestCRL test fails

### ISSUE THREAD

**Issue by ConiKost** [zhaozg/lua-openssl#231]
- `uname -a` or OS info: Linux Galactica 5.11.11-gentoo #1 SMP Sun Apr 4 23:29:23 CEST 2021 x86_64 Intel(R) Atom(TM) CPU C2758 @ 2.40GHz GenuineIntel GNU/Linux

- `openssl version` or OPENSSL_VERSION_TEXT in your opensslv.h: OpenSSL 1.1.1k  25 Mar 2021
- `lua -v` or `luajit -v`: LuaJIT 2.0.5 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/
- `lua -e "print(require'openssl'.version())" or `luajit -e "print(require'openssl'.version())"`: 0.8.0	Lua 5.1	OpenSSL 1.1.1k  25 Mar 2021

**Problem details**
```
# Starting class: TestCRL
not ok 8	TestCRL.testNew
#   5.x509_crl.lua:48: bad argument #2 to 'updateTime' (value must after #2)
```

**Steps/codes to reproduce the bug**
Run test TestCMS

**Expected result**
TestCRL will not fail.

**Comment by zhaozg** [comment]
fixed in https://github.com/zhaozg/lua-openssl/commit/3fbe31a6d6e76ddac08d5da8eaa1c00fa54060e7

I guess that you build it in 32 bits modes.
