### ISSUE TITLE
Installation failure: 

### ISSUE THREAD

**Issue by jnaadjie** [zhaozg/lua-openssl#234]
- Alpine(Unix)- (Docker openresty/openresty:alpine-fat:)
- `openssl 0.8.0-6` (https://luarocks.org/openssl-0.8.0-6.src.rock)
- `lua 5.1` or luajit-2.1:
- `lua -e "print(require'openssl'.version()): 269488319" or `luajit -e "print(require'openssl'.version())": 269488319`:

**Problem details**
Have been using openresty/openresty:alpine-fat Docker file for over a year. 
Docker build recently fails with the following error:

`Error: Failed installing dependency: https://luarocks.org/openssl-0.8.0-6.src.rock - failed deploying files. The following files were not installed:
#11 89.94 /usr/local/openresty/luajit/lib/lua/5.1/openssl.so`

**Steps/codes to reproduce the bug**
docker file: 

`FROM openresty/openresty:alpine-fat

ENV RESTY_DIR=/opt/openresty
ENV PUBLIC_DIR=/usr/local/openresty/nginx/html/public

COPY build ${RESTY_DIR}/build
COPY Makefile ${RESTY_DIR}/Makefile
COPY lb-nginx-1.0-2.rockspec ${RESTY_DIR}/lb-nginx-1.0-2.rockspec

WORKDIR ${RESTY_DIR}

RUN apk add --update --no-cache \
        openssl-dev \
        openssl \
        nodejs nodejs-npm \
        lua-lzmq \
        git \
        && \
    ln -s /usr/local/openresty/luajit/bin/luajit-2.1.0-beta3 /usr/bin/lua && \
    luarocks make lb-nginx-1.0-2.rockspec && \
    apk del \
        git`

Using rockspec file which includes openssl dependency

luarocks make mydep.rockspec

`package = "lb-nginx"
version = "1.0-2"
source = {
  url = "...",
  dir = ".",
}
dependencies = {
  "lua",
  "luasec",
  "etlua",
  "lapis = 1.8.1",
  "pgmoon",
  "penlight",
  "linenoise",
  "luarepl",
  "uuid",
  "bit32",
  "lunitx",
  "lbase64",
  "openssl",
  "lua-resty-jwt"
}

build = {
  type = "make",
  build_target = "luarocks-build",
  install_pass = false,
}
`

**Expected result**
installation failure for openssl

**Additional context**
using make displays various warning messages
 /usr/include/openssl/pem.h:252:77: note: expected 'void **' but argument is of type 'char **'
#11 82.25   252 | void *PEM_ASN1_read_bio(d2i_of_void *d2i, const char *name, BIO *bp, void **x,
#11 82.25       |                                                                      ~~~~~~~^
#11 82.26 src/ocsp.c: In function 'openssl_ocsp_response_read':
#11 82.26 src/ocsp.c:307:30: warning: passing argument 1 of 'PEM_ASN1_read_bio' from incompatible pointer type [-Wincompatible-pointer-types]
#11 82.26   307 |   OCSP_RESPONSE *res = pem ? PEM_read_bio_OCSP_RESPONSE(bio, NULL, NULL)
#11 82.26       |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
#11 82.26       |                              |
#11 82.26       |                              char * (*)()
#11 82.26 In file included from src/openssl.h:23,
#11 82.26                  from src/ocsp.c:7:
#11 82.26 /usr/include/openssl/pem.h:252:38: note: expected 'void * (*)(void **, const unsigned char **, long int)' but argument is of type 'char * (*)()'
#11 82.26   252 | void *PEM_ASN1_read_bio(d2i_of_void *d2i, const char *name, BIO *bp, void **x,
#11 82.26       |                         ~~~~~~~~~~~~~^~~

**Comment by zhaozg** [comment]
welcome PR

**Comment by zhaozg** [comment]
Caused by upstream: https://github.com/openssl/openssl/issues/2548, not fix
