### ISSUE TITLE
Question: openssl.random strong argument

### ISSUE THREAD

**Issue by Bilal2453** [zhaozg/lua-openssl#236]
According to the [docs](https://zhaozg.github.io/lua-openssl/modules/openssl.html#random), `strong` is used to generate "Strong random bytes" though looking at the [relevant code](https://github.com/zhaozg/lua-openssl/blob/master/src/openssl.c#L334-L357) it seems to be executing the same exact block of code whether `strong` was true or false. Despite that, looking at the [OpenSSL docs](https://www.openssl.org/docs/man1.1.1/man3/RAND_bytes.html), `int RAND_bytes(unsigned char *buf, int num);` there is no such argument at all.

So what does this argument really do? if the same block of code executed and if no such thing exists in OpenSSL? I thought I may have been missing something somewhere.

**Comment by Duckwhale** [comment]
This was exactly what had me scratching my head, and from what I can see things are as follows:

In https://www.openssl.org/docs/man1.1.1/man3/RAND_bytes.html it is noted:

> RAND_pseudo_bytes() was deprecated in OpenSSL 1.1.0; use RAND_bytes() instead.

And indeed, the [docs for 1.1.0](https://www.openssl.org/docs/man1.1.0/man3/RAND_bytes.html) state as much:

> RAND_pseudo_bytes() has been deprecated. Users should use RAND_bytes() instead. 

I think the function call itself was replaced in https://github.com/zhaozg/lua-openssl/commit/5515e26c60fb496770b4881bbcebfe6d1b558a8a, though it seems like at the very least the documentation should've been updated (and TBH, I'd also just remove the branch as it will inevitably confuse future readers).

From a end-user standpoint I'd also wonder if there's another way to generate pseudo-random numbers via OpenSSL now, or why they decided to remove it. It seems like there may be use cases where one could want a similar functionality, or perhaps it's better to use ``rand`` directly?

**Comment by zhaozg** [comment]
clear in https://github.com/zhaozg/lua-openssl/commit/7ab54b9dc0a1c672d2df16dc9bfee98c226e992b
and doc https://zhaozg.github.io/lua-openssl/modules/openssl.html#random update
