### ISSUE TITLE
Support Lua 5.4

### ISSUE THREAD

**Issue by glguy** [zhaozg/lua-openssl#246]
I've been using your library with Lua 5.4 since the Lua 5.4 release. It's been working great (for the subset of the library I use).

Is there anything that needs to be done before the upper-bound on Lua can be raised?

**Comment by zhaozg** [comment]
> Is there anything that needs to be done before the upper-bound on Lua can be raised?

Nothing need to do, lua-openssl support luajit, lua 5.[1-4], please look at https://github.com/zhaozg/lua-openssl/actions/workflows/ci.yml
