### ISSUE TITLE
Is openssl 1.0.2 supported with lua 5.1 release?

### ISSUE THREAD

**Issue by dhruv459** [zhaozg/lua-openssl#247]
- `uname -a` or OS info: Linux ip<....>-aws ... ~18.04.1-Ubuntu SMP Wed Jul 28 03:04:50 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- `openssl version` or OPENSSL_VERSION_TEXT in your opensslv.h: Company maintained version of openssl-1.0.2
- `lua -v` or `luajit -v`: Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
- `lua -e "print(require'openssl'.version())" or `luajit -e "print(require'openssl'.version())"`: 
lua: (command line):1: module 'openssl' not found:
	no field package.preload['openssl']
	no file './openssl.lua'
	no file '/usr/local/share/lua/5.1/openssl.lua'
	no file '/usr/local/share/lua/5.1/openssl/init.lua'
	no file '/usr/local/lib/lua/5.1/openssl.lua'
	no file '/usr/local/lib/lua/5.1/openssl/init.lua'
	no file '/usr/share/lua/5.1/openssl.lua'
	no file '/usr/share/lua/5.1/openssl/init.lua'
	no file './openssl.so'
	no file '/usr/local/lib/lua/5.1/openssl.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/openssl.so'
	no file '/usr/lib/lua/5.1/openssl.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	(command line):1: in main chunk
	[C]: ?

**Problem details**
We have a gateway application that is build with openresty and it uses lua 5.1 as of now. I have provided the openssl lib_dir path
while installing different components of lua. Earlier we were using openssl-1.1.1k version and it was working fine but now we
are trying to switch (switching backwards for compliance purpose) to an internally maintained version of openssl which is essentially openssl-1.0.2.  And while doing so we are getting the following error.

nginx: [error] init_by_lua error: error loading module 'ssl.core' from file '/usr/local/lib/lua/5.1/ssl.so':
 nginx[12619]: #011/usr/local/lib/lua/5.1/ssl.so: undefined symbol: OPENSSL_sk_num

OPENSSL_sk_num variable is present in libssl.so.1.1.1 file but I could not locate the same variable in libssl.so.1.0.2 so wanted to confirm if using 1.0.2 version of openssl is possible or not.

**Comment by zhaozg** [comment]
Where you download lua-openssl?  Are you use the lua-openssl, maybe others.
