### ISSUE TITLE
Luarocks.org module does not support 5.4

### ISSUE THREAD

**Issue by jprjr** [zhaozg/lua-openssl#258]
Hi there - it looks like all the CI for Lua 5.4 is passing, but the published module on Luarocks still lists Lua < 5.4: https://luarocks.org/modules/zhaozg/openssl

**Comment by zhaozg** [comment]
closed in https://github.com/zhaozg/lua-openssl/commit/1df8e533dfd5f1c248fa4c79bdab13ed627929bf
