### ISSUE TITLE
ECC verify is not working as expected

### ISSUE THREAD

**Issue by samtest3234** [zhaozg/lua-openssl#262]
- `uname -a` or OS info: Macbook Monterey
- `openssl version` or OPENSSL_VERSION_TEXT in your opensslv.h: 1.1.1
- `lua -v` or `luajit -v`: 5.4.3
- `lua -e "print(require'openssl'.version())"` or `luajit -e "print(require'openssl'.version())"`: 0.8.2	Lua 5.4	OpenSSL 1.1.1n  15 Mar 2022

**Problem details**
Even if you truncate the signature, ec:verify() still returns true

**Steps/codes to reproduce the bug**

```
local ec = grp:generate_key()
local dgst = "Hello World"
local der = ec:sign(dgst, 'sha256')
local der2 = der:sub(1, 20)

print(ec:verify(dgst, der, 'sha256')) -- this is true
print(ec:verify(dgst .. "x", der, 'sha256')) -- this should be false
print(ec:verify(dgst, der, 'sha1')) -- this should also be false
print(ec:verify(dgst, der2, 'sha256')) -- this should also be false
```

The output is 
```
true
false
true
true
```

**Expected result**

```
true
false
false
false
```

**Additional context**

According to https://manpages.debian.org/experimental/libssl-doc/ECDSA_verify.3ssl.en.html

```
ECDSA_verify() verifies that the signature in sig of size siglen is a valid ECDSA signature of 
the hash value dgst of size dgstlen using the public key eckey. The parameter type is ignored.
```

Parameter `type` is ignored, this explains why the `sha1` still returns true

**Comment by samtest3234** [comment]
Ok, see this page

https://github.com/openssl/openssl/issues/8766

```
 * returns
 *      1: correct signature
 *      0: incorrect signature
 *     -1: error
 ```
 
The return value of do_verify(), and verify() as well, is integer. And if we convert it to boolean, both 1 and -1 resolve to True (I guess).

**Comment by samtest3234** [comment]
A workaround

```
print(openssl.clear_error())
print(ec:verify(dgst, der, 'sha256'))
print(openssl.errors())
```

openssl.errors() will be non-blank if there is any error

**Comment by zhaozg** [comment]
Thank you, I fixed this in HEAD.
