### ISSUE TITLE
Compilation will fail with >=clang-16: src/ocsp.c: error: incompatible function pointer types passing char ( )() to parameter of type d2i

### ISSUE THREAD

**Issue by ConiKost** [zhaozg/lua-openssl#265]
- `uname -a` or OS info: ```Linux Galactica 6.0.7-gentoo #1 SMP PREEMPT_DYNAMIC Sun Nov 6 14:26:32 CET 2022 x86_64 Intel(R) Atom(TM) CPU C2758 @ 2.40GHz GenuineIntel GNU/Linux```
- `openssl version` or OPENSSL_VERSION_TEXT in your opensslv.h: ```OpenSSL 1.1.1s  1 Nov 2022```
- `lua -v` or `luajit -v`: ```Lua 5.4.4  Copyright (C) 1994-2022 Lua.org, PUC-Rio```
- `lua -e "print(require'openssl'.version())" or `luajit -e "print(require'openssl'.version())"`: ```0.8.2-1```

**Problem details**

**Steps/codes to reproduce the bug**

1. ... Use clang-16 or newer for compilation

**Expected result**
Compilation works with clang-16 or newer.

**Additional context**
```
Wno-unused-function -DPTHR
clang -pipe -march=native -fno-diagnostics-color -O2 -Werror=implicit-function-declaration -Werror=implicit-int -fPIC  -pipe -march=native -fno-diagnostics-color -O2 -Werror=implicit-function-declaration -Werror=implicit-int -I/usr/include/lua5.4   -Wall -Wno-unused-value -Wno-unused-function -DPTHR
src/ocsp.c:124:29: error: incompatible function pointer types passing 'char *(*)()' to parameter of type 'd2i_of_void *' (aka 'void *(*)(void **, const unsigned char **, long)') [-Werror,-Wincompatible-function-pointer-types]
  OCSP_REQUEST *req = pem ? PEM_read_bio_OCSP_REQUEST(bio, NULL, NULL)
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This is due clang-16 applying `-Wincompatible-function-pointer-types` as default.

**Comment by zhaozg** [comment]
https://github.com/search?q=repo%3Aopenssl%2Fopenssl+%5B-Wincompatible-pointer-types%5D&type=issues will show more.

**Comment by ConiKost** [comment]
I am not sure, what you wan't to say with it? Sure, some others projects can also have this issue in future. Never the less, it's something, which should be fixed in future, when Clang-16 will more widespread.

**Comment by zhaozg** [comment]
I means this kind issues are caused by `openssl` official version,  I try to avoid and fix these issues in `lua-openssl`, but some low level change must be done in `openssl`.

So we need use lastest version(v3.1) of `openssl` ,  or wait upstream to fix in openssl v1.1.1

**Comment by zhaozg** [comment]
English is not my first language,  so please forgive me for not expressing it properly or say nothing.

**Comment by zhaozg** [comment]
I do some test with clang-15, and avoid some errors, now I have no better ideas.

And thank you very much.

**Comment by ConiKost** [comment]
Thanks!
