### ISSUE TITLE
Compile with C++

### ISSUE THREAD

**Issue by paolonevis** [zhaozg/lua-openssl#267]
I have compiled Lua with C++.
This means, that I need to compile lua-openssl as well with C++, otherwise all lua symbols are not known (because of the different mangled name).

This are the changes I had to do:
 - replaced class with clazz
 - replaced new with nev
 - replaced private with priwate
 - replaced _Bool with bool (inside an ifdef _cplusplus)
 - put the #include "lua.h" outside the 'extern "C"'...

I tried to create a branch and open a pull request with my changes, but I didn't get the permission.
It would be nice if you could integrate those changes into the code.

Many thanks

**Comment by zhaozg** [comment]
lua-openssl not support build as C++.
