### ISSUE TITLE
Build without external dependencies

### ISSUE THREAD

**Issue by a1div0** [zhaozg/lua-openssl#274]
Hello!
Please tell me - is there a way to build this library without external dependencies?

```
error loading module 'lua-openssl' from file '/__w/megafon-cdi/megafon-cdi/.rocks/lib/tarantool/lua-openssl.so':
	libssl.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by zhaozg** [comment]
I add a commit https://github.com/zhaozg/lua-openssl/commit/a5cac5ff1ab26af25eb0d6e3bd9d7b7c46f5fbea
to support static link openssl, please use  `make OPENSSL_STATIC=1`.

And I have no idea howto do that with lua-rocks builtin compile system, welcome some PR.
