### ISSUE TITLE
gcm support

### ISSUE THREAD

**Issue by libla** [zhaozg/lua-openssl#297]
when use cipher.get("aes-128/256-gcm"), EVP_DecryptFinal_ex will always return 0, because tag verify fails.

**Comment by zhaozg** [comment]
Ref to

1. https://github.com/zhaozg/lua-openssl#example-7-aes-128-gcm
2. https://github.com/zhaozg/lua-openssl/blob/master/test/issue%23156.lua
3. https://www.openssl.org/docs/man1.0.2/man3/EVP_aes_256_gcm.html
4. https://wiki.openssl.org/index.php/EVP_Authenticated_Encryption_and_Decryption
