### ISSUE TITLE
How to create RSA public key from `e` and `n` values as big num instances.

### ISSUE THREAD

**Issue by creationix** [zhaozg/lua-openssl#33]
I'm loading ssh public keys from github and want to convert them to openssl public keys to verify some signatures I'm creating.

I've parsed the ssh format and have the raw `e` and `n` values using `bn.text()` and some custom parsing code I wrote.
I can't figure out how to go from this to an instance of the openssl public key format.

Do you have any tips or docs on this matter?

**Comment by zhaozg** [comment]
firstly, check master out, because fixed bug.
then, consider below code.

```lua
local pkey = require'openssl'.pkey
local unpack = unpack or table.unpack

    function testRSA()
        --create new rsa key paire
        local nrsa =  {'rsa',1024,3}
        local rsa = pkey.new(unpack(nrsa))
        print(rsa)
        local k1 = pkey.get_public(rsa)
        assert(not k1:is_private())
        local t = k1:parse ()
        assert(t.bits==1024)
        assert(t.type=='rsa')
        assert(t.size==128)
        local r = t.rsa
        t = r:parse()
        -- t include n,e field openssl.bn types.
        for k,v in pairs(t) do
            print(k,v)
        end
        -- let pkey.new to know which alg, alg='rsa' will use n,e to create a publickey
        t.alg = 'rsa'
        local r2 = pkey.new(t)
        print('private:',r2:is_private())
        -- do some test
        local msg = openssl.random(128-11)
        
        local out = pkey.encrypt(r2,msg)
        local raw = pkey.decrypt(rsa,out)
        assert(msg==raw)
    end
    
    testRSA();
```

**Comment by zhaozg** [comment]
https://github.com/zhaozg/lua-openssl/commit/96398158588ae41af9b8749f425a54d40f84d91a

**Comment by creationix** [comment]
So, in your example, `t` is a normal lua table and I can create public keys directly using tables of that form?

Here is the workaround I'm using for now.  I manually generate the DER data and then use `openssl.read` to import it into lua-openssl. https://github.com/luvit/lit/blob/master/modules/creationix/ssh-rsa.lua#L134-L159

**Comment by zhaozg** [comment]
Yes,  t is lua table, and should have alg,n,e for rsa public key.
I sugest to use http://zhaozg.github.io/lua-openssl/modules/pkey.html#read to load openssl key, than use key:parse() to get all factor for keys, and low object (eg,rsa) can be parse again.

**Comment by zhaozg** [comment]
@creationix, I think this will do same thing.

```lua
function exports.toPublicKey(data)
  -- Convert to der format so openssl can read it
  local e, n = exports.decode(data)
  local rsa = {alg='rsa',n=n,e=e}
  local t = rsa:parse().rsa:parse()
  assert(t.e == e and t.n == n)

  return rsa
end
```

**Comment by zhaozg** [comment]
@creationix, how about this problem, may I close it?

**Comment by creationix** [comment]
Yep worked great, thanks!
https://github.com/luvit/lit/blob/00ff6b9c5a157acae2180f1e2ae64c842c7b3bee/app/modules/creationix/ssh-rsa.lua#L134-L149
