### ISSUE TITLE
`ssl_ctx:options` inconsistent with doc

### ISSUE THREAD

**Issue by moteus** [zhaozg/lua-openssl#36]
Doc say `options(bool, string)` or `options(string,string)`
But as I can see it `options(bool, number)` or `options(number)`
Also because of that it is a bug in `ssl.lua`
```Lua
    if params.options then
        local args = {}
        for i=1,#params.options do
            table.insert(arg,params.options[i]) -- !!! note you use `arg` instead of `args`
        end
        ctx:options(unpack(args))
    end
```

**Comment by zhaozg** [comment]
thanks

**Comment by zhaozg** [comment]
In options() really have a bug, now I fixed, and update document.
In real word, my ugly document need more work.
https://github.com/zhaozg/lua-openssl/commit/ecb45be6ec79d7253b8985359e2785b9382d2c4e 
and thanks again.
