### ISSUE TITLE
Request: SSL_CTX_set_session_cache_mode

### ISSUE THREAD

**Issue by rphillips** [zhaozg/lua-openssl#38]
This function isn't bound yet to ```lua-openssl```. At the minimum, setting the cache to off would be super useful.

**Comment by zhaozg** [comment]
accept

**Comment by zhaozg** [comment]
please try https://github.com/zhaozg/lua-openssl/commit/e91f9f7cf546e1978f6a523a06cf3d512b95b8b8

**Comment by rphillips** [comment]
awesome. thank you!
