### ISSUE TITLE
Segmentation fault on crl.parse

### ISSUE THREAD

**Issue by moteus** [zhaozg/lua-openssl#40]
Windows XP/OpenSSL 1.0.1c
Problem that on line [crl.c:533](https://github.com/zhaozg/lua-openssl/blob/master/src/crl.c#L533) `revoked->reason` is `-1`
```C
    X509_REVOKED *revoked = sk_X509_REVOKED_value(crl->crl->revoked, i);
    lua_newtable(L);

#if OPENSSL_VERSION_NUMBER > 0x10000000L
    AUXILIAR_SET(L, -1, "CRLReason", reason_flags[revoked->reason].lname, string);
#else
```

If I remove `#if` block and use  variant based on `X509_REVOKED_get_ext_d2i` It works and get result `Unused`

**Comment by zhaozg** [comment]
please try https://github.com/zhaozg/lua-openssl/commit/4c266cb4858896aa54d51a1db75519ec67cd3e48.
