### ISSUE TITLE
`PUSH_ASN1_INTEGER` push negative value

### ISSUE THREAD

**Issue by moteus** [zhaozg/lua-openssl#41]
With my cert I get `cert->cert_info->serialNumber` as negative integer (`V_ASN1_NEG_INTEGER`)
(This is certificate from Avast Free Antivirus).
So I get error when call `PUSH_ASN1_INTEGER(L, cert->cert_info->serialNumber);`
So I think is it valid to update `openssl_push_asn1` as
```C
int openssl_push_asn1(lua_State* L, ASN1_STRING* string, int type, int utf8)
{
  if(type && (
    (string->type != type) && (string->type != (type|V_ASN1_NEG))
  ))
  {
    luaL_error(L, "need %s asn1, but get %s",asn1_typestring(type),asn1_typestring(string->type));
    return 0;
  }

  switch(string->type){
  case V_ASN1_INTEGER:
  case V_ASN1_NEG_INTEGER:
 ```

If it need I can create PR tomorrow.

**Comment by zhaozg** [comment]
change to 
```lua
int openssl_push_asn1(lua_State* L, ASN1_STRING* string, int type, int utf8)
{
  if (type && (string->type&type == type))
  {
    luaL_error(L, "need %s asn1, but get %s",asn1_typestring(type),asn1_typestring(string->type));
    return 0;
  }
```

**Comment by zhaozg** [comment]
Thanks very much.

**Comment by moteus** [comment]
But you also need add `V_ASN1_NEG_INTEGER` to proceed value in `switch` statement.

**Comment by zhaozg** [comment]
please review https://github.com/zhaozg/lua-openssl/blob/6a17893f8717cbb5ae207c5fc6c97425b51368c4/src/asn1.c#L722-L731
