### ISSUE TITLE
Test error

### ISSUE THREAD

**Issue by moteus** [zhaozg/lua-openssl#46]
When I run tes I get one error
```
>>> TestX509Name.testAll failed
1.x509_name.lua:60: Error, substring "utf8" was not found in string "bmp:ι"
```
If I comment `assertStrContains(tostring(v),'utf8')` then I get error
```
>>> TestX509Name.testAll failed
1.x509_name.lua:62: expected: "utf8:эЧФэЫОыз¦"
actual: "bmp:-Lг+¦·"
```

PS. this error exists at least at e99b949890ff17df154037720ee73561181bfd24

**Comment by zhaozg** [comment]
please consider this, https://github.com/zhaozg/lua-openssl/issues/26
I think maybe your use openssl old version

**Comment by moteus** [comment]
The same error on Travis.

PS. test.lua does not return error code in case when test fail.

**Comment by zhaozg** [comment]
I build some openssl newest version at https://github.com/zhaozg/openssl-win32, can handle utf8 correctly.
I will recheck this problems

**Comment by moteus** [comment]
I just build OpenSSL 1.0.2 and it works correctly.

You can close or try fix it for older version.

**Comment by zhaozg** [comment]
openssl 1.0.2 released at http://www.openssl.org/source/openssl-1.0.2.tar.gz.
