### ISSUE TITLE
API design

### ISSUE THREAD

**Issue by moteus** [zhaozg/lua-openssl#48]
Currently API is not consistent and intuitive at all.
E.g. `context:set_verify()` can be used to get information.
So I suggest to make name/semantic convention.
E.g. we can use one function to get/set just like `context:options()` or use
prefix `set_` to setter.

**Comment by zhaozg** [comment]
In my means, I want to use one function to do get and set operation.
set_verify maybe my lost eye.
@moteus  is a kind,meticulous and par excellence programmer, thanks.
Please keep give me advice and bugs.
