### ISSUE TITLE
Update test with new version of LuaUnit

### ISSUE THREAD

**Issue by moteus** [zhaozg/lua-openssl#52]
Last version deos not export module to global space so tests fials.
I do not know more about this or how stable current status of LuaUnit.
So may by for now just use `luaunit.lua` file from test directory and do not update it 
while installing on Travis.

**Comment by zhaozg** [comment]
fixed.https://github.com/zhaozg/lua-openssl/commit/626f4dce9417168c86e82c6be778f7aefa69ae0c
