### ISSUE TITLE
Using submodules leads to fail install via LuaRocks.

### ISSUE THREAD

**Issue by moteus** [zhaozg/lua-openssl#53]
See for example https://travis-ci.org/moteus/lua-lluv-ssl/builds/52266303.
You can also check out this [discassion](https://github.com/keplerproject/luarocks/issues/169)
But I do not know good solution. (For release I think it is possible build `src.rock`)

**Comment by zhaozg** [comment]
fixed by https://github.com/zhaozg/lua-openssl/commit/9dbbe3eb9bf34fadf6290092b718800e01f824ae
