### ISSUE TITLE
Better error reporting.

### ISSUE THREAD

**Issue by moteus** [zhaozg/lua-openssl#58]
At first I do not know is it possible at all but recently I try figure out why I can not connect to some server using SSL connection. The reasan was that server reply with TLSv1.0 HELLO when I use TLSv1.2. Error code from ssl:handshake() is just SSL_ERROR but on server there was all OK.
I can figure out the reason only with Wireshark.
So may be there exists way to have more detail error messages for ssl function.

**Comment by zhaozg** [comment]
can you try https://github.com/zhaozg/lua-openssl/blob/master/ldoc/openssl.lua#L28-L33

**Comment by moteus** [comment]
Thanks. It works.
Can you help me to understand right way to implement error handling
E.g. this is function to implement SSL decoding (bases on your luv ssl example)
```Lua
-- self._out - BIO_mem
-- self._ssl - SSL context
-- self._obuffer - buffer that contain data that shuld be encoded

-- this function returns next chunk of encoded data
function SSLDecoder:output() 
  -- Here we should clear OpenSSL error queue?
  ssl.last_error(true)

  local chunk, err = self._out:read()
  if not chunk then
    -- shuld we check err or just call `last_error`
    local code, reason = ssl.last_error()
    if code then --[[handle error]]  end
  elseif  #chunk > 0 then return chunk end

  while not self._obuffer:empty() do
    -- next chunk do decode
    chunk = self._obuffer:read_some(OCHUNK_SIZE)

    local n, err = self._ssl:write(chunk)
    -- same as in case of `self._out:read()`?
   ...
  
```
You can check out my code [here](https://github.com/moteus/lua-lluv-ssl/blob/master/src/lua/lluv/ssl.lua#L245-L270)

**Comment by zhaozg** [comment]
ok, my pleasure

**Comment by moteus** [comment]
Questions in comments in code snippets.

**Comment by zhaozg** [comment]
Sorry for  can't give solution right now, but I can write some article to show how to handle it with lua-openssl in some days.

**Comment by moteus** [comment]
Thanks. It would be halpful.

**Comment by zhaozg** [comment]
https://github.com/zhaozg/lua-openssl#howto-5-handle-fail-or-error
https://github.com/zhaozg/lua-openssl/blob/master/ldoc/ssl.lua#L218

```lua
-- self._out - BIO_mem
-- self._ssl - SSL context
-- self._obuffer - buffer that contain data that shuld be encoded

-- this function returns next chunk of encoded data
function SSLDecoder:output() 
  ssl.error(true)   --better to clear error queue

  local chunk,  err = self._out:read()
  if chunk then return chunk  end --success

  if chunk==nil then --fail if ssl or syscall
       print('ERROR with:'..err
  end
  assert(chunk==false)  
  if err==0 then
     print('SSL has been closed')
     return
  end
  print('want to',err) --  want_read/write/x509_lookup/... SSL not fail, but want API do something

  local n, err = self._ssl:write(chunk)
  -- n is bytes count successfully write, for read that is input string,
  -- err same with read.
```

**Comment by moteus** [comment]
I have some questions

`self._out:read()` is read from `BIO_mem` object so in `local chunk,  err = self._out:read()`
`chunk` can be only `nil` or `string` but not false because it is not SSL function.

```Lua
  local chunk,  err = self._out:read()

  if not chunk then -- Error and we get error code
       return nil, openssl.error(err) -- get error info
  end

  -- we can not get chunk == false because this is just BIO operation?
  assert(type(chunk) == 'string')

  -- success only if chunk not empty?
  -- I get chunk == '' while ssl:write returns false, 'want_read'
  if #chunk > 0 then return chunk  end

  while ... do
    -- here we try to encode next chunk from input stream and try read again
    chunk = .... next decoded chunk

    local n, err = self._ssl:write(chunk)

    if not n then
      if n == nil then -- ssl/syscall - check out last error
        return nil, openssl.error()
      end

      assert(n == false)

      if err==0 then
         print('SSL has been closed') --just connection really closed
         return nil, 'EOF'
      end

      -- is it possible get err == 'want_write' after write operation.
      -- if yes should I just increase chunk or write next chunk?
    
      return ''
    end

    -- repeat read from self._out:read()
```

**Comment by zhaozg** [comment]
That is right.
   `self._out:read()` is read from `BIO_mem` object so in `local chunk,  err = self._out:read()`
   `chunk` can be only `nil` or `string` but not false because it is not SSL function.

Your code is right too.
when bio:read() return string '', should continue to do something and retry read,
