### ISSUE TITLE
Binding request for SSL_CTX_use_certificate_chain

### ISSUE THREAD

**Issue by rphillips** [zhaozg/lua-openssl#59]
The alternative for ```ctx:verify_locations(params.cafile,params.capath)``` would be ```SSL_CTX_use_certificate_chain``` within the API. This would allow applications to pragmatically set the certificate chain to verify against.

**Comment by rphillips** [comment]
Perhaps SSL_CTX_use_certificate_chain was changed in the newer openssl API.

**Comment by rphillips** [comment]
Ah hah! SSL_CTX_add_extra_chain_cert

**Comment by rphillips** [comment]
hmm. there is a binding for this too... looking into it more... sorry for the churn

**Comment by zhaozg** [comment]
ctx:verify_locations(cafile,capath) https://github.com/zhaozg/lua-openssl/blob/master/ldoc/ssl.lua#L40-L44

ctx:add(cacert,{extra_certs}} has been support,https://github.com/zhaozg/lua-openssl/blob/master/ldoc/ssl.lua#L40-L44

**Comment by rphillips** [comment]
Thanks for the tip... Found out we were missing a root CA cert. sorry
