### ISSUE TITLE
Explicit close/cleanup methods

### ISSUE THREAD

**Issue by moteus** [zhaozg/lua-openssl#62]
Could you please add explicit close methods to objects.

E.g. I use Cipher context. And after I call `ctx:final()` I no need this object and can close it and do not wait gc. Is it valid at all using `ctx` object after `final` method? In my use case it gives me wrong results. (GNTP server can not decode such data). So to encrypt/decript parts of message I use `new->update->final` sequence for each part.

`close` method for cipher/hash could work as final+cleanup. (ofcourse decode error in final should not prevent close context)

**Comment by zhaozg** [comment]
Call twice final without paramter will return same result ,this to compat to luacrypto, but bug when have paramater,I will fix it，and lookinto your GNTP

**Comment by moteus** [comment]
>Call twice final of digest CTX without paramter will return same result

Yes. I forgot about that.
But I stil think that `close` and `reset` method could be convinient.
`reset` method allows do not allocate at least new Lua userdata. And may be use same OpenSSL object.
`close` method allows explicitly destroy OpenSSL object. Lua gc has no idea about how many resources contains in this object.

>I need more check my code to reproduce and lookinto your GNTP, welcome any reproduce bug code.

I am not shure that this is bug.
```Lua
key, iv = ..
ctx = Cipher.new('AES-192-CBC', true,  key, iv, true)
s1 = ctx:update(m1) .. (ctx:final() or '')
s2 = ctx:update(m2) .. (ctx:final() or '')
-- and
ctx = Cipher.new('AES-192-CBC', true,  key, iv, true)
s3 = ctx:update(m2) .. (ctx:final() or '')
```
In this case should s2 be same as s3?

**Comment by zhaozg** [comment]
Hi @moteus

  1. I will add close method support Digest ,HMAC, Cipher ctx, support free object immediately not wait for gc.
  2. Digest ctx support reset method, but HMAC, Cipher ctx will not, because inner state not have a copy origin key and iv, you know than IV will changed when do update or final operation.
  3. ctx design to support process long message, because iv changed, so different result of s1,s3,and s3,   s1~=s2,s1~=s3,s2~=s3
  4. http://zhaozg.github.io/lua-openssl/modules/cipher.html#openssl.cipher, http://zhaozg.github.io/lua-openssl/modules/cipher.html#encrypt, http://zhaozg.github.io/lua-openssl/modules/cipher.html#decrypt will better for short message process.

**Comment by zhaozg** [comment]
Should I make of a copy of key in lua-openssl? I think it's a bad idea, because security.

**Comment by moteus** [comment]
> Digest ctx support reset method, but HMAC, Cipher ctx will not, because inner state not have a copy origin key and iv, you know that IV will changed when do update or final operation.

I agree. But you can pass `iv` as argument.
You can checkout my version that I made for LuaCrypto (https://github.com/moteus/luacrypto/tree/stream)

Also when I write ZipWriter I found that zip encryption uses AES-CBC mode but increment of IV vector is different than used in OpenSSL. So to implement that encryption I need to use custum iv increment function ([AesFileEncrypt.lua](https://github.com/moteus/ZipWriter/blob/master/lua/ZipWriter/encrypt/aes/AesFileEncrypt.lua#L164-L165)). And to implement such function string representation is not good choice. It would be convinient use array of bytes as IV. Also I think about collback to custom iv increment function
```Lua
ctx:set_iv_increment(function(buf)
-- here `buf` is mutable byte array that callback can change
end)
```
