### ISSUE TITLE
verify signatures

### ISSUE THREAD

**Issue by rphillips** [zhaozg/lua-openssl#64]
It would be extremely useful for the signature verification function pubkey:verify() to support ```update``` and then ```final``` separately. Currently, all the data needs to be read into a lua buffer and then passed to the verify function. The update and final approach would allow the data to be streamed through.

**Comment by zhaozg** [comment]
OK，Let me look into it, if OpenSSL support I'll add it

**Comment by rphillips** [comment]
https://www.openssl.org/docs/crypto/EVP_VerifyInit.html

I believe the code already uses these functions.

**Comment by zhaozg** [comment]
closed

**Comment by rphillips** [comment]
Sweet! Thanks
