### ISSUE TITLE
pkey.read format='auto' needs some improvements

### ISSUE THREAD

**Issue by dol** [zhaozg/lua-openssl#69]
The auto format detection of pkey.read is limited to RSA keys only. EC keys in the format of DER are not auto detected. This is due to the limitation of the detection => bio_is_der.

```
if (len == sizeof(head) && head[0] == 0x30 && head[1] == 0x82)
```

EC keys have a different second byte. If I'm not wrong, the second byte is the length of the ASN.1 sequence.
To get a clearer view on the problem run the following command for EC keys:
```
openssl ecparam -list_curves|fgrep :|tr -d ' '|cut -d: -f1|xargs -I{} sh -c "openssl ecparam -name {} -genkey -noout -outform DER|od -tx1|fgrep 0000000"
```

The same problems happens as well with small RSA keys:
```
seq 5 12|xargs -I{} sh -c 'openssl genrsa $(dc -e "2 {} ^ p") 2>/dev/null|openssl rsa -inform pem -outform der 2>/dev/null|od -tx1|fgrep 0000000'
```

**Comment by zhaozg** [comment]
assigned to @zhaozg
