### ISSUE TITLE
pkey.new(factors) for type 'ec' does not support binary key data

### ISSUE THREAD

**Issue by dol** [zhaozg/lua-openssl#70]
According to the documentation of pkey.new(factors) the following should be possible:
```
 new (factors)
    Parameters:
        when arg is ec, table may with D,X,Y,Z,both are binary string or openssl.bn
```
```
local pkey = require 'openssl'.pkey
ec = pkey.new({alg='ex', x=<binary string>, y=<binary string>, d=<binary string>}
```

Due to the usage of 'BN_get' in [pkey.c](https://github.com/zhaozg/lua-openssl/blob/59b1fd9deba4dc6070e70bc79bfd84a896e6208b/src/pkey.c#L427) the parameters for x, y, d are limited to a bignum as string or a hex encoded string with a leading 'x'.

This problem only applies for the type 'ec'. The other types are handles correctly with the usage of the macro 'OPENSSL_PKEY_SET_BN'.

**Comment by zhaozg** [comment]
please check.

**Comment by dol** [comment]
Worked. Thx
