### ISSUE TITLE
Rename project?

### ISSUE THREAD

**Issue by daurnimator** [zhaozg/lua-openssl#72]
I had a confusing bug report today due to the conflicting name.
Your project uses the same `require` string "openssl" as the (older) project [luaossl](https://github.com/wahern/luaossl)

**Comment by zhaozg** [comment]
Are you sure that.
I begin my project from Jul 2, 2011, you can look in https://code.google.com/p/lua-openssl/source/detail?r=1

**Comment by daurnimator** [comment]
> Are you sure that.
> I begin my project from Jul 2, 2011, you can look in https://code.google.com/p/lua-openssl/source/detail?r=1
> even on github Jul 3, 2011.

Ah true. I must have got the dates confused somehow.
I'll ask the luaossl author about renaming....

**Comment by zhaozg** [comment]
in my memory，these projs not conflint , maybe you install compat libs in Lua-openSSL

**Comment by daurnimator** [comment]
> in my memory，these projs not conflint ,

They both use the require string "openssl".
e.g. the following code will do different things depending which of luaossl and lua-openssl you install most recently: 
```lua
print(require"openssl".version())
```

luaossl's manual is here: https://25thandclement.com/~william/projects/luaossl.pdf
