### ISSUE TITLE
Free all occurrences of BN_new() 

### ISSUE THREAD

**Issue by dol** [zhaozg/lua-openssl#76]
BN_new() is used at some places. In some places of the code the BIGNUM's are not cleared according to the docs => https://www.openssl.org/docs/manmaster/crypto/BN_new.html

**Comment by zhaozg** [comment]
Please not worry about it, We use BN_new to create BIGNUM object, there are three way to do free operation.

1. explicit  BN_free it 
2. as single lua object, it will be gc.
3. as a part of a complex lua object,(eg, pkey) when  complex gc, BN object will be gc.

**Comment by dol** [comment]
Good to know. Thx
