### ISSUE TITLE
about base64

### ISSUE THREAD

**Issue by wonderwj** [zhaozg/lua-openssl#77]
base64编码会自动换行，而解码的时候是设置了 BIO_FLAGS_BASE64_NO_NL标识，不处理换行，所以造成对长数据进行base64编码之后，用此函数的解码会失败。

为了通用，是否应该在编码是也设置BIO_set_flags(b64, BIO_FLAGS_BASE64_NO_NL); ？？

**Comment by zhaozg** [comment]
有道理，马上进行处理

**Comment by zhaozg** [comment]
--- base64 encode or decode
-- @tparam string|bio input
-- @tparam[opt=true] boolean encode true to encoed, false to decode
-- @tparam[opt=false] boolean NO_NL true without newline, false with newline
-- @treturn string
function base64() end
