### ISSUE TITLE
Release on LuaRocks

### ISSUE THREAD

**Issue by jirutka** [zhaozg/lua-openssl#82]
Please release the last version on [LuaRocks](https://luarocks.org/modules/zhaozg/openssl).

**Comment by zhaozg** [comment]
Done

**Comment by zhaozg** [comment]
http://luarocks.org/modules/zhaozg/openssl

**Comment by jirutka** [comment]
I mean stable version, i.e. [0.4.1](https://github.com/zhaozg/lua-openssl/tree/0.4.1), so it can be installed from LuaRocks stable, just with `luarocks install openssl` instead of `luarocks install --server=http://luarocks.org/dev openssl`.

**Comment by moteus** [comment]
Any plans make release?
