### ISSUE TITLE
src/digest.c : ligne 412

### ISSUE THREAD

**Issue by abdelmouneim** [zhaozg/lua-openssl#83]
this ligne : 
412:      ret = EVP_DigestVerifyFinal(ctx, (const unsigned char*) signature, signature_len);
must be replaced by this one : 
 412:     ret = EVP_DigestVerifyFinal(ctx, (unsigned char*) signature, signature_len);
------------------------------------------------------------------------------------------------------------
this is the output of man EVP_DigestVerifyFinal
NAME
       EVP_DigestVerifyInit, EVP_DigestVerifyUpdate, EVP_DigestVerifyFinal -
       EVP signature verification functions

SYNOPSIS
        #include <openssl/evp.h>

        int EVP_DigestVerifyInit(EVP_MD_CTX *ctx, EVP_PKEY_CTX **pctx,
                               const EVP_MD *type, ENGINE *e, EVP_PKEY *pkey);
        int EVP_DigestVerifyUpdate(EVP_MD_CTX *ctx, const void *d, unsigned int cnt);
        int EVP_DigestVerifyFinal(EVP_MD_CTX *ctx, unsigned char *sig, size_t siglen);

**Comment by zhaozg** [comment]
Thanks, but please look at https://www.openssl.org/docs/manmaster/crypto/EVP_DigestVerifyInit.html
or https://www.openssl.org/docs/man1.0.2/crypto/EVP_DigestVerifyInit.html, that is different with https://www.openssl.org/docs/man1.0.0/crypto/EVP_DigestVerifyInit.html

And I think keep const should more safe.

**Comment by abdelmouneim** [comment]
Yep, you're right.  Great work by the way.
