### ISSUE TITLE
Custom increment of IV.

### ISSUE THREAD

**Issue by moteus** [zhaozg/lua-openssl#90]
OpenSSL provide only one way to increment IV vector.
But in some cases need other algorithm. E.g. in my [ZipWriter](https://github.com/moteus/ZipWriter/blob/master/lua/ZipWriter/encrypt/aes/AesFileEncrypt.lua#L208-L209) library I have to use

``` Lua
    -- Increment IV vector
    inc_nonce(nonce)
    -- Calculate encrypt key
    local tmp = openssl.cipher.encrypt(aes_name, H(nonce), aes_key)
    -- Encrypt data in buffer
    for i = 1, #chunk do buf[i] = bit.bxor( sbyte(chunk, i), sbyte(tmp, i) ) end
```

To emulate CTR with custom increment IV
I think about alternative.
First I implement [resetiv](https://github.com/moteus/luacrypto/blob/stream/src/lcrypto.c#L728-L757) method for LuaCrypto library. But this is not solve fully problem because you still have to use `xor` on Lua side.
I think about callback which accept/return IV as array of bytes or may be big number.

One more option is set some common used increment function.
In my bgcrypto I use this [function](https://github.com/moteus/lua-bgcrypto-aes/blob/7468f3a7bff2fa06e35c165384b6544e13920d2d/src/laes.c#L2274)

``` Lua
  -- create context
  local encrypt = aes.ctr_encrypter()
  -- set IV increment mode to firward increment
  encrypt:set_inc_mode("fi")
  -- Set IV to `0x01 0x00 0x00...`
  encrypt:open(key, '\1' .. ('\0'):rep(aes.BLOCK_SIZE - 1))
```

**Comment by zhaozg** [comment]
are you means we should support https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/crypto/modes/ctr128.c?
