### ISSUE TITLE
Ubuntu 16.04 error on module load

### ISSUE THREAD

**Issue by bakpakin** [zhaozg/lua-openssl#94]
When loading the module, I get the error:

```
error loading module 'openssl' from file '/usr/local/lib/lua/5.1/openssl.so':
    /usr/local/lib/lua/5.1/openssl.so: undefined symbol: X509_ALGOR_cmp
stack traceback:
    [C]: at 0x004525b0
    [C]: in function 'require'
    stdin:1: in main chunk
    [C]: at 0x004044a0
```

I installed with luarocks, and am using luajit.

**Comment by zhaozg** [comment]
I'm sure X509_ALGOR_cmp will works on openssl v1.0.2, so OPENSSL_VERSION_NUMBER should > 0x10002000L.
1.  can you tell me you openssl version with `openssl version`?
2. and how do you build it.

**Comment by bakpakin** [comment]
I am using the openSSL version that is installed by default on Ubuntu 16.04 (sudo apt-get insall openssl). apt-get reports the version as `1.0.2g-1ubuntu4.1`.

Here is the result from the openSSL commandline tool.
```
OpenSSL> version
OpenSSL 1.0.2g-fips  1 Mar 2016
```
I am indeed on a version 1.0.2

The package worked fine when I removed the function in src/xalgor.c and compiled.

**Comment by zhaozg** [comment]
that's surprised, follow this

**Comment by zhaozg** [comment]
Are you use right include dir? how do you build?

**Comment by milani** [comment]
I used luarocks on ubuntu 16.04 and got the same error. Openssl version is the same as above.

**Comment by zhaozg** [comment]
I installed ubuntu 16.04, and do some check. 
  
1. The bug occurs, 
![image](https://cloud.githubusercontent.com/assets/542599/21803474/34e9df1e-d765-11e6-913d-315345c622cf.png)

2.openssl header with X509_ALGOR_cmp 
![image](https://cloud.githubusercontent.com/assets/542599/21803510/5c36b312-d765-11e6-944b-6bae2667192f.png)

3. But after link, X509_ALGOR_cmp keep undefined,
![image](https://cloud.githubusercontent.com/assets/542599/21803563/8931d3f6-d765-11e6-851b-52da4fface0d.png)

4. Check so, can't found X509_ALGOR_cmp, but others define.
![image](https://cloud.githubusercontent.com/assets/542599/21803634/dc0b0c82-d765-11e6-9467-4d0c19b5c08f.png)

5. So I think it's bug of ubuntu libssl-dev,  please compile openssl from source code and retest.

**Comment by milani** [comment]
I can confirm that compiling openssl 1.1.0 from source fixed the problem.

**Comment by JuMeBe** [comment]
Hello @milani. I guess you recompiled lua-openssl after rebuilding openssl 1.1.0, right? However, my attempts at doing so failed because 1.1.0 seem to lack (have removed) function `ECDSA_set_method`, which is defined in 1.0.2.
Did you encounter this problem? Do you remember how did you solve it?
Or maybe @zhaozg has some insight?

**Comment by zhaozg** [comment]
@JuMeBe Yes, are you right, int ECDSA_set_method renamed to EC_KEY_set_method in 1.1.0, that need do some update for that, before I do that, you can use HEAD~1 on Ubuntu

**Comment by doctorguile** [comment]
Just want to add my findings in case someone ran into this on ubuntu16

I tried to compile with openssl-1.1.0h but it seems like it is not backward compatible with openssl-1.0.2 so there are a lot of undefined symbols

Next I compiled openssl-1.0.2o from source and it installed to /usr/local/ssl/ by default
and pkg-config cannot find it.

So I modified Makefile like so

```
OPENSSL_CFLAGS  ?= $(shell PKG_CONFIG_PATH=/usr/local/ssl/lib/pkgconfig/ pkg-config openssl --cflags)
OPENSSL_LIBS    ?= $(shell PKG_CONFIG_PATH=/usr/local/ssl/lib/pkgconfig/ pkg-config openssl --static --libs)
```

lua-openssl compiles fine and installs to /usr/local/lib/lua/5.1/openssl.so

Next, a simple test shows the same undefined symbol X509_ALGOR_cmp as mentioned above

```
# /usr/local/bin/luajit ~/test.lua
/usr/local/bin/luajit: error loading module 'openssl' from file '/usr/local/lib/lua/5.1/openssl.so':
	/usr/local/lib/lua/5.1/openssl.so: undefined symbol: X509_ALGOR_cmp
stack traceback:
	[C]: at 0x0044d100
	[C]: in function 'require'
	/root/test.lua:1: in main chunk
	[C]: at 0x004042b0
```

The issue is that the loader will use the system wide libssl.so by default 

```
# ldd /usr/local/lib/lua/5.1/openssl.so
	linux-vdso.so.1 =>  (0x00007ffd97f6d000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f7638266000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f7637e22000)
	libluajit-5.1.so.2 => /usr/local/lib/libluajit-5.1.so.2 (0x00007f7637bb1000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f76377e6000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f76375e2000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f76372d9000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f76370c2000)
	/lib64/ld-linux-x86-64.so.2 (0x0000563f570e7000)
```

So finally specify LD_LIBRARY_PATH explicitly and it ran fine.

```
# LD_LIBRARY_PATH=/usr/local/ssl/lib:/lib:/usr/lib:/usr/local/lib /usr/local/bin/luajit ~/test.lua 

Lua 5.1
OpenSSL 1.0.2o  27 Mar 2018
0.7.1
```

Not sure if there's a way to run it without specifying LD_LIBRARY_PATH or  changing /etc/ld.so.conf

**Comment by zhaozg** [comment]
hit this at https://travis-ci.org/zhaozg/lua-openssl/jobs/531065957

**Comment by jl2035** [comment]
I don't feel comfortable following @doctorguile instructions, as I totally don't understand. Is there a less hacky way of fixing this problem?

My version is: OpenSSL 1.1.1  11 Sep 2018.
Should I also be compiling older versions of openssl like @doctorguile?

Adding LD_LIBRARY_PATH doesn't solve the problem for me.

Should this issue be reopened? I also installed using luarocks.

**Comment by Legrandin** [comment]
Why was this issue closed?
The problem is clearly still there with Ubuntu 16 and its openssl 1.0.2g.

Users should not be asked to recompile openssl either...
